%% -*- coding: latin-1 -*-
{"Access Control Lists","Llista de Control d'Accés"}.
{"Access Rules","Regles d'Accés"}.
{"Add User","Afegir usuari"}.
{"April","Abril"}.
{"August","Agost"}.
{"Backup","Guardar còpia de seguretat"}.
{"Birthday","Aniversari"}.
{"Change User Password","Canviar Contrasenya d'Usuari"}.
{"Chatroom configuration modified","Configuració de la sala de xat modificada"}.
{"Chatroom is created","La sala s'ha creat"}.
{"Chatroom is destroyed","La sala s'ha destruït"}.
{"Chatroom is started","La sala s'ha iniciat"}.
{"Chatroom is stopped","La sala s'ha aturat"}.
{"City","Ciutat"}.
{"Configuration","Configuració"}.
{"Country","Pais"}.
{"Database","Base de dades"}.
{"December","Decembre"}.
{"Delete User","Eliminar Usuari"}.
{"Dump to Text File","Exportar a fitxer de text"}.
{"Email","Email"}.
{"Encoding for server ~b","Codificació pel servidor ~b"}.
{"End User Session","Finalitzar Sesió d'Usuari"}.
{"Enter the text you see","Introdueix el text que veus"}.
{"Family Name","Cognom"}.
{"February","Febrer"}.
{"Friday","Divendres"}.
{"From ~s","De ~s"}.
{"Full Name","Nom complet"}.
{"Get Number of Online Users","Obtenir Número d'Usuaris Connectats"}.
{"Get Number of Registered Users","Obtenir Número d'Usuaris Registrats"}.
{"Get User Last Login Time","Obtenir la última connexió d'Usuari"}.
{"Get User Password","Obtenir Contrasenya d'usuari"}.
{"Get User Statistics","Obtenir Estadístiques d'Usuari"}.
{"has been banned","Has sigut banejat"}.
{"has been kicked because of an affiliation change","Has sigut expulsat a causa d'un canvi d'afiliació"}.
{"has been kicked because of a system shutdown","Has sigut expulsat perquè el sistema s'ha apagat"}.
{"has been kicked because the room has been changed to members-only","Has sigut expulsat perquè la sala ha canviat a sols membres"}.
{"has been kicked","Has sigut expulsat"}.
{" has set the subject to: "," ha posat l'assumpte: "}.
{"Import Directory","Importar directori"}.
{"Import File","Importar fitxer"}.
{"is now known as","ara es conegut com"}.
{"Jabber ID","ID Jabber"}.
{"January","Gener"}.
{"joins the room","Entrar a la sala"}.
{"July","Juliol"}.
{"June","Juny"}.
{"leaves the room","Deixar la sala"}.
{"March","Març"}.
{"May","Maig"}.
{"Middle Name","Segon nom"}.
{"Monday","Dilluns"}.
{"Name","Nom"}.
{"Nickname","Sobrenom"}.
{"November","Novembre"}.
{"October","Octubre"}.
{"Organization Name","Nom de la organizació"}.
{"Organization Unit","Unitat de la organizació"}.
{"Password ~b","Contrasenya ~b"}.
{"Ping","Ping"}.
{"Port ~b","Port ~b"}.
{"private, ","privat"}.
{"Restart Service","Reiniciar el Servei"}.
{"Restore","Restaurar"}.
{"Room Configuration","Configuració de la sala"}.
{"Room Occupants","Nombre d'ocupants"}.
{"Saturday","Dissabte"}.
{"Search Results for ","Resultat de la búsqueda"}.
{"September","Setembre"}.
{"Server ~b","Servidor ~b"}.
{"Shut Down Service","Apager el Servei"}.
{"Start Modules","Iniciar mòduls"}.
{"Stop Modules","Parar mòduls"}.
{"Sunday","Diumenge"}.
{"The CAPTCHA is valid.","El CAPTCHA es vàlid."}.
{"This IP address is blacklisted in ~s","Esta adreça IP està a la llista negra en ~s"}.
{"Thursday","Dijous"}.
{"Too many (~p) failed authentications from this IP address (~s). The address will be unblocked at ~s UTC","Massa autenticacions (~p) han fallat des d'aquesta adreça IP (~s). L'adreça serà desbloquejada en ~s UTC"}.
{"To ~s","A ~s"}.
{"Tuesday","Dimarts"}.
{"Wednesday","Dimecres"}.
