%% -*- coding: latin-1 -*-
{"Access Control Lists","Seznamy přístupových práv (ACL)"}.
{"Access Rules","Pravidla přístupů"}.
{"Add User","Přidat uživatele"}.
{"April",". dubna"}.
{"August",". srpna"}.
{"Backup","Zálohovat"}.
{"Birthday","Datum narození"}.
{"Change User Password","Změnit heslo uživatele"}.
{"Chatroom configuration modified","Nastavení diskuzní místnosti bylo změněno"}.
{"Chatroom is created","Konference vytvořena"}.
{"Chatroom is destroyed","Konference zrušena"}.
{"Chatroom is started","Konference spuštěna"}.
{"Chatroom is stopped","Konference zastavena"}.
{"City","Město"}.
{"Configuration","Konfigurace"}.
{"Country","Země"}.
{"Database","Databáze"}.
{"December",". prosince"}.
{"Delete User","Smazat uživatele"}.
{"Dump to Text File","Uložit do textového souboru"}.
{"Email","E-mail"}.
{"Encoding for server ~b","Kódování pro server ~b"}.
{"End User Session","Ukončit sezení uživatele"}.
{"Enter the text you see","Zadejte text, který vidíte"}.
{"Family Name","Příjmení"}.
{"February",". února"}.
{"Friday","Pátek"}.
{"From ~s","Od  ~s"}.
{"Full Name","Celé jméno"}.
{"Get Number of Online Users","Získat počet online uživatelů"}.
{"Get Number of Registered Users","Získat počet registrovaných uživatelů"}.
{"Get User Last Login Time","Získat čas podleního přihlášení uživatele"}.
{"Get User Password","Získat heslo uživatele"}.
{"Get User Statistics","Získat statistiky uživatele"}.
{"has been banned","byl(a) zablokován(a)"}.
{"has been kicked because of an affiliation change","byl(a) vyhozen(a) kvůli změně přiřazení"}.
{"has been kicked because of a system shutdown","byl(a) vyhozen(a), protože dojde k vypnutí systému"}.
{"has been kicked because the room has been changed to members-only","byl(a) vyhozen(a), protože mísnost je nyní pouze pro členy"}.
{"has been kicked","byl(a) vyhozen(a) z místnosti"}.
{" has set the subject to: "," změnil(a) téma na: "}.
{"Import Directory","Import adresáře"}.
{"Import File","Import souboru"}.
{"is now known as","se přejmenoval(a) na"}.
{"Jabber ID","Jabber ID"}.
{"January",". ledna"}.
{"joins the room","vstoupil(a) do místnosti"}.
{"July",". července"}.
{"June",". června"}.
{"leaves the room","opustil(a) místnost"}.
{"March",". března"}.
{"May",". května"}.
{"Middle Name","Druhé jméno"}.
{"Monday","Pondělí"}.
{"Name","Jméno"}.
{"Nickname","Přezdívka"}.
{"November",". listopadu"}.
{"October",". října"}.
{"Organization Name","Název firmy"}.
{"Organization Unit","Oddělení"}.
{"Password ~b","Heslo ~b"}.
{"Ping","Ping"}.
{"Port ~b","Port ~b"}.
{"private, ","soukromá, "}.
{"Restart Service","Restartovat službu"}.
{"Restore","Obnovit"}.
{"Room Configuration","Nastavení místnosti"}.
{"Room Occupants","Počet účastníků"}.
{"Saturday","Sobota"}.
{"Search Results for ","Výsledky hledání pro "}.
{"September",". září"}.
{"Server ~b","Server ~b"}.
{"Shut Down Service","Vypnout službu"}.
{"Start Modules","Spustit moduly"}.
{"Stop Modules","Zastavit moduly"}.
{"Sunday","Neděle"}.
{"The CAPTCHA is valid.","CAPTCHA souhlasí."}.
{"This IP address is blacklisted in ~s","IP adresa je blokována na ~s"}.
{"Thursday","Čtvrtek"}.
{"Too many (~p) failed authentications from this IP address (~s). The address will be unblocked at ~s UTC","Příliš mnoho (~p) chybných pokusů o přihlášení z této IP adresy (~s). Adresa bude zablokována do ~s UTC"}.
{"To ~s","Pro ~s"}.
{"Tuesday","Úterý"}.
{"Wednesday","Středa"}.
