%% -*- coding: latin-1 -*-
{"Access Control Lists","Zugangskontroll-Listen (ACL)"}.
{"Access Rules","Zugangsregeln"}.
{"Add User","Benutzer hinzufügen"}.
{"April","April"}.
{"August","August"}.
{"Backup","Datensicherung"}.
{"Birthday","Geburtsdatum"}.
{"Change User Password","Benutzer-Passwort ändern"}.
{"Chatroom configuration modified","Chatraum-Konfiguration geändert"}.
{"Chatroom is created","Chatraum wurde erstellt"}.
{"Chatroom is destroyed","Chatraum wurde entfernt"}.
{"Chatroom is started","Chatraum wurde gestartet"}.
{"Chatroom is stopped","Chatraum wurde beendet"}.
{"City","Stadt"}.
{"Configuration","Konfiguration"}.
{"Country","Land"}.
{"Database","Datenbank"}.
{"December","Dezember"}.
{"Delete User","Benutzer löschen"}.
{"Dump to Text File","Ausgabe in Textdatei"}.
{"Email","E-Mail"}.
{"Encoding for server ~b","Kodierung für Server ~b"}.
{"End User Session","Benutzer-Sitzung beenden"}.
{"Enter the text you see","Geben sie den Text den sie sehen ein"}.
{"Family Name","Nachname"}.
{"February","Februar"}.
{"Friday","Freitag"}.
{"From ~s","Von ~s"}.
{"Full Name","Vollständiger Name"}.
{"Get Number of Online Users","Anzahl der angemeldeten Benutzer abrufen"}.
{"Get Number of Registered Users","Anzahl der registrierten Benutzer abrufen"}.
{"Get User Last Login Time","letzte Anmeldezeit abrufen"}.
{"Get User Password","Benutzer-Passwort abrufen"}.
{"Get User Statistics","Benutzer-Statistiken abrufen"}.
{"has been banned","wurde gebannt"}.
{"has been kicked because of an affiliation change","wurde wegen Änderung des Mitgliederstatus entfernt"}.
{"has been kicked because of a system shutdown","wurde wegen einer Systemabschaltung entfernt"}.
{"has been kicked because the room has been changed to members-only","wurde entfernt weil der Raum auf Nur-Mitglieder umgestellt wurde"}.
{"has been kicked","wurde entfernt"}.
{" has set the subject to: "," hat das Thema geändert auf: "}.
{"Import Directory","Verzeichnis importieren"}.
{"Import File","Datei importieren"}.
{"is now known as","ist nun bekannt als"}.
{"Jabber ID","Jabber ID"}.
{"January","Januar"}.
{"joins the room","betretet den Raum"}.
{"July","Juli"}.
{"June","Juni"}.
{"leaves the room","verlässt den Raum"}.
{"March","März"}.
{"May","Mai"}.
{"Middle Name","Zweiter Vorname"}.
{"Monday","Montag"}.
{"Name","Vorname"}.
{"Nickname","Benutzername"}.
{"November","November"}.
{"October","Oktober"}.
{"Organization Name","Name der Organisation"}.
{"Organization Unit","Abteilung"}.
{"Password ~b","Passwort ~b"}.
{"Ping","Ping"}.
{"Port ~b","Port ~b"}.
{"private, ","privat, "}.
{"Restart Service","Dienst neustarten"}.
{"Restore","Wiederherstellung"}.
{"Room Configuration","Raum-Konfiguration"}.
{"Room Occupants","Teilnehmer in diesem Raum"}.
{"Saturday","Samstag"}.
{"Search Results for ","Suchergebnisse für "}.
{"September","September"}.
{"Server ~b","Server ~b"}.
{"Shut Down Service","Dienst herunterfahren"}.
{"Start Modules","Module starten"}.
{"Stop Modules","Module stoppen"}.
{"Sunday","Sonntag"}.
{"The CAPTCHA is valid.","Die Verifizierung ist gültig."}.
{"This IP address is blacklisted in ~s","Diese IP Adresse ist blockiert in ~s"}.
{"Thursday","Donnerstag"}.
{"Too many (~p) failed authentications from this IP address (~s). The address will be unblocked at ~s UTC","Zu viele (~p) fehlgeschlagene Anmeldeversuche von dieser IP Adresse (~s). Die Adresse wird bis ~s UTC blockiert."}.
{"To ~s","An ~s"}.
{"Tuesday","Dienstag"}.
{"Wednesday","Mittwoch"}.
