%% -*- coding: latin-1 -*-
{"Access Control Lists","Λίστες Ελέγχου Πρόσβασης"}.
{"Access Rules","Κανόνες Πρόσβασης"}.
{"Add User","Προσθήκη Χρήστη"}.
{"April","Απρίλιος"}.
{"August","Αύγουστος"}.
{"Backup","Αποθήκευση Αντιγράφου Ασφαλείας"}.
{"Birthday","Γενέθλια"}.
{"Change User Password","Αλλαγή Κωδικού Πρόσβασης Χρήστη"}.
{"Chatroom configuration modified","Διαμόρφωση Αίθουσaς σύνεδριασης τροποποιηθηκε"}.
{"Chatroom is created","Η αίθουσα σύνεδριασης  δημιουργήθηκε"}.
{"Chatroom is destroyed","Η αίθουσα σύνεδριασης διαγράφηκε"}.
{"Chatroom is started","Η αίθουσα σύνεδριασης έχει ξεκινήσει"}.
{"Chatroom is stopped","Η αίθουσα σύνεδριασης έχει σταματήσει"}.
{"City","Πόλη"}.
{"Configuration","Διαμόρφωση"}.
{"Country","Χώρα"}.
{"Database","Βάση δεδομένων"}.
{"December","Δεκέμβριος"}.
{"Delete User","Διαγραφή Χρήστη"}.
{"Dump to Text File","Αποθήκευση σε αρχείο κειμένου"}.
{"Email","Email"}.
{"Encoding for server ~b","Κωδικοποίηση για διακομιστή ~b"}.
{"End User Session","Τερματισμός Συνεδρίας Χρήστη"}.
{"Enter the text you see","Πληκτρολογήστε το κείμενο που βλέπετε"}.
{"Family Name","Επώνυμο"}.
{"February","Φεβρουάριος"}.
{"Friday","Παρασκευή"}.
{"From ~s","Από ~s"}.
{"Full Name","Ονοματεπώνυμο"}.
{"Get Number of Online Users","Έκθεση αριθμού συνδεδεμένων χρηστών"}.
{"Get Number of Registered Users","Έκθεση αριθμού εγγεγραμμένων χρηστών"}.
{"Get User Last Login Time","Έκθεση Τελευταίας Ώρας Σύνδεσης Χρήστη"}.
{"Get User Password","Έκθεση Κωδικού Πρόσβασης Χρήστη"}.
{"Get User Statistics","Έκθεση Στατιστικών Χρήστη"}.
{"has been banned","έχει απαγορευθεί"}.
{"has been kicked because of an affiliation change","Έχει αποβληθεί λόγω αλλαγής υπαγωγής"}.
{"has been kicked because of a system shutdown","αποβλήθηκε λόγω τερματισμού συστήματος"}.
{"has been kicked because the room has been changed to members-only","αποβλήθηκε επειδή η αίθουσα αλλάξε γιά μέλη μόνο"}.
{"has been kicked","αποβλήθηκε "}.
{" has set the subject to: "," έχει θέσει το θέμα σε: "}.
{"Import Directory","Εισαγωγή κατάλογου αρχείων"}.
{"Import File","Εισαγωγή αρχείων"}.
{"is now known as","είναι τώρα γνωστή ως"}.
{"Jabber ID","Ταυτότητα Jabber"}.
{"January","Ιανουάριος"}.
{"joins the room","συνδέετε στην αίθουσα"}.
{"July","Ιούλιος"}.
{"June","Ιούνιος"}.
{"leaves the room","εγκαταλείπει την αίθουσα"}.
{"March","Μάρτιος"}.
{"May","Μάιος"}.
{"Middle Name","Πατρώνυμο"}.
{"Monday","Δευτέρα"}.
{"Name","Όνομα"}.
{"Nickname","Ψευδώνυμο"}.
{"November","Νοέμβριος"}.
{"October","Οκτώβριος"}.
{"Organization Name","Όνομα Οργανισμού"}.
{"Organization Unit","Μονάδα Οργανισμού"}.
{"Password ~b","Κωδικός πρόσβασης ~b"}.
{"Ping","Πινγκ"}.
{"Port ~b","Θύρα ~b"}.
{"private, ","ιδιωτικό,"}.
{"Restart Service","Επανεκκίνηση Υπηρεσίας"}.
{"Restore","Επαναφορά Αντιγράφου Ασφαλείας"}.
{"Room Configuration","Διαμόρφωση Αίθουσας σύνεδριασης"}.
{"Room Occupants","Συμετεχόντες Αίθουσας σύνεδριασης"}.
{"Saturday","Σάββατο"}.
{"Search Results for ","Αποτελέσματα αναζήτησης για "}.
{"September","Σεπτέμβριος"}.
{"Server ~b","Διακομιστής  ~b"}.
{"Shut Down Service","Κλείσιμο Υπηρεσίας"}.
{"Start Modules","Εκκίνηση Modules"}.
{"Stop Modules","ΠαύσηModules"}.
{"Sunday","Κυριακή"}.
{"The CAPTCHA is valid.","Το CAPTCHA είναι έγκυρο."}.
{"Thursday","Πέμπτη"}.
{"To ~s","Πρώς ~s"}.
{"Tuesday","Τρίτη"}.
{"Wednesday","Τετάρτη"}.
