%% -*- coding: latin-1 -*-
{"Access Control Lists","Atingokontrol-listoj"}.
{"Access Rules","Atingo-reguloj"}.
{"Add User","Aldonu Uzanton"}.
{"April","Aprilo"}.
{"August","Aŭgusto"}.
{"Backup","Faru Sekurkopion"}.
{"Birthday","Naskiĝtago"}.
{"Change User Password","Ŝanĝu pasvorton de uzanto"}.
{"Chatroom configuration modified","Agordo de babilejo ŝanĝita"}.
{"Chatroom is created","Babilejo kreita"}.
{"Chatroom is destroyed","Babilejo neniigita"}.
{"Chatroom is started","Babilejo lanĉita"}.
{"Chatroom is stopped","Babilejo haltita"}.
{"City","Urbo"}.
{"Configuration","Agordo"}.
{"Country","Lando"}.
{"Database","Datumbazo"}.
{"December","Decembro"}.
{"Delete User","Forigu Uzanton"}.
{"Dump to Text File","Skribu en plata tekst-dosiero"}.
{"Email","Retpoŝto"}.
{"Encoding for server ~b","Enkodigo por servilo ~b"}.
{"End User Session","Haltigu Uzant-seancon"}.
{"Enter the text you see","Enmetu montrita teksto"}.
{"Family Name","Lasta Nomo"}.
{"February","Februaro"}.
{"Friday","Vendredo"}.
{"From ~s","De ~s"}.
{"Full Name","Plena Nomo"}.
{"Get Number of Online Users","Montru nombron de konektataj uzantoj"}.
{"Get Number of Registered Users","Montru nombron de registritaj uzantoj"}.
{"Get User Last Login Time","Montru tempon de lasta ensaluto"}.
{"Get User Password","Montru pasvorton de uzanto"}.
{"Get User Statistics","Montru statistikojn de uzanto"}.
{"has been banned","estas forbarita"}.
{"has been kicked because of an affiliation change","estas forpelita pro aparteneca ŝanĝo"}.
{"has been kicked because of a system shutdown","estas forpelita pro sistem-haltigo"}.
{"has been kicked because the room has been changed to members-only","estas forpelita ĉar la babilejo fariĝis sole por membroj"}.
{"has been kicked","estas forpelita"}.
{" has set the subject to: "," ŝanĝis la temon al: "}.
{"Import Directory","Importu dosierujo"}.
{"Import File","Importu dosieron"}.
{"is now known as","nun nomiĝas"}.
{"Jabber ID","Jabber ID"}.
{"January","Januaro"}.
{"joins the room","eniras la babilejo"}.
{"July","Julio"}.
{"June","Junio"}.
{"leaves the room","eliras la babilejo"}.
{"March","Marĉo"}.
{"May","Majo"}.
{"Middle Name","Meza Nomo"}.
{"Monday","Lundo"}.
{"Name","Nomo"}.
{"Nickname","Kaŝnomo"}.
{"November","Novembro"}.
{"October","Oktobro"}.
{"Organization Name","Organiz-nomo"}.
{"Organization Unit","Organiz-parto"}.
{"Password ~b","Pasvorto ~b"}.
{"Ping","Sondaĵo"}.
{"Port ~b","Pordo ~b"}.
{"private, ","privata, "}.
{"Restart Service","Restartu Servon"}.
{"Restore","Restaŭru"}.
{"Room Configuration","Babilejo-agordo"}.
{"Room Occupants","Nombro de ĉeestantoj"}.
{"Saturday","Sabato"}.
{"Search Results for ","Serĉ-rezultoj de "}.
{"September","Septembro"}.
{"Server ~b","Servilo ~b"}.
{"Shut Down Service","Haltigu Servon"}.
{"Start Modules","Startu Modulojn"}.
{"Stop Modules","Haltigu Modulojn"}.
{"Sunday","Dimanĉo"}.
{"The CAPTCHA is valid.","La CAPTCHA ĝustas"}.
{"This IP address is blacklisted in ~s","Ĉi tiu IP-adreso estas barata in ~s"}.
{"Thursday","Ĵaŭdo"}.
{"Too many (~p) failed authentications from this IP address (~s). The address will be unblocked at ~s UTC","Tro da malsukcesaj aŭtentprovoj (~p) de ĉi tiu IP-adreso (~s). La adreso estos malbarata je ~s UTC."}.
{"To ~s","Al ~s"}.
{"Tuesday","Mardo"}.
{"Wednesday","Merkredo"}.
