%% -*- coding: latin-1 -*-
{"Access Control Lists","Listas de Control de Acceso"}.
{"Access Rules","Reglas de Acceso"}.
{"Add User","Añadir usuario"}.
{"April","abril"}.
{"August","agosto"}.
{"Backup","Guardar copia de seguridad"}.
{"Birthday","Cumpleaños"}.
{"Change User Password","Cambiar contraseña de usuario"}.
{"Chatroom configuration modified","Configuración de la sala modificada"}.
{"Chatroom is created","Se ha creado la sala"}.
{"Chatroom is destroyed","Se ha destruido la sala"}.
{"Chatroom is started","Se ha iniciado la sala"}.
{"Chatroom is stopped","Se ha detenido la sala"}.
{"City","Ciudad"}.
{"Configuration","Configuración"}.
{"Country","País"}.
{"Database","Base de datos"}.
{"December","diciembre"}.
{"Delete User","Borrar usuario"}.
{"Dump to Text File","Exportar a fichero de texto"}.
{"Email","correo"}.
{"Encoding for server ~b","Codificación del servidor ~b"}.
{"End User Session","Cerrar sesión de usuario"}.
{"Enter the text you see","Teclea el texto que ves"}.
{"Family Name","Apellido"}.
{"February","febrero"}.
{"Friday","viernes"}.
{"From ~s","De ~s"}.
{"Full Name","Nombre completo"}.
{"Get Number of Online Users","Ver número de usuarios conectados"}.
{"Get Number of Registered Users","Ver número de usuarios registrados"}.
{"Get User Last Login Time","Ver fecha de la última conexión de usuario"}.
{"Get User Password","Ver contraseña de usuario"}.
{"Get User Statistics","Ver estadísticas de usuario"}.
{"has been banned","ha sido bloqueado"}.
{"has been kicked because of an affiliation change","ha sido expulsado por un cambio de su afiliación"}.
{"has been kicked because of a system shutdown","ha sido expulsado porque el sistema se va a detener"}.
{"has been kicked because the room has been changed to members-only","ha sido expulsado porque la sala es ahora solo para miembros"}.
{"has been kicked","ha sido expulsado"}.
{" has set the subject to: "," ha puesto el asunto: "}.
{"Import Directory","Importar directorio"}.
{"Import File","Importar fichero"}.
{"is now known as","se cambia el nombre a"}.
{"Jabber ID","Jabber ID"}.
{"January","enero"}.
{"joins the room","entra en la sala"}.
{"July","julio"}.
{"June","junio"}.
{"leaves the room","sale de la sala"}.
{"March","marzo"}.
{"May","mayo"}.
{"Middle Name","Segundo nombre"}.
{"Monday","lunes"}.
{"Name","Nombre"}.
{"Nickname","Apodo"}.
{"November","noviembre"}.
{"October","octubre"}.
{"Organization Name","Nombre de la organización"}.
{"Organization Unit","Unidad de la organización"}.
{"Password ~b","Contraseña ~b"}.
{"Ping","Ping"}.
{"Port ~b","Puerto ~b"}.
{"private, ","privado"}.
{"Restart Service","Reiniciar el servicio"}.
{"Restore","Restaurar"}.
{"Room Configuration","Configuración de la sala"}.
{"Room Occupants","Ocupantes de la sala"}.
{"Saturday","sábado"}.
{"Search Results for ","Buscar resultados por "}.
{"September","septiembre"}.
{"Server ~b","Servidor ~b"}.
{"Shut Down Service","Detener el servicio"}.
{"Start Modules","Iniciar módulos"}.
{"Stop Modules","Detener módulos"}.
{"Sunday","domingo"}.
{"The CAPTCHA is valid.","El CAPTCHA es válido."}.
{"This IP address is blacklisted in ~s","Esta dirección IP está en la lista negra en ~s"}.
{"Thursday","jueves"}.
{"Too many (~p) failed authentications from this IP address (~s). The address will be unblocked at ~s UTC","Demasiadas (~p) autenticaciones fallidas de esta dirección IP (~s). La dirección será desbloqueada en ~s UTC"}.
{"To ~s","A ~s"}.
{"Tuesday","martes"}.
{"Wednesday","miércoles"}.
