%% -*- coding: latin-1 -*-
{"Access Control Lists","Droits (ACL)"}.
{"Access Rules","Règles d'accès"}.
{"Add User","Ajouter un utilisateur"}.
{"April","Avril"}.
{"August","Août"}.
{"Backup","Sauvegarde"}.
{"Birthday","Date d'anniversaire"}.
{"Change User Password","Changer le mot de passe de l'utilisateur"}.
{"Chatroom configuration modified","Configuration du salon modifiée"}.
{"Chatroom is created","Le salon de discussion est créé"}.
{"Chatroom is destroyed","Le salon de discussion est détruit"}.
{"Chatroom is started","Le salon de discussion a démarré"}.
{"Chatroom is stopped","Le salon de discussion est stoppé"}.
{"City","Ville"}.
{"Configuration","Configuration"}.
{"Country","Pays"}.
{"Database","Base de données"}.
{"December","Décembre"}.
{"Delete User","Supprimer l'utilisateur"}.
{"Dump to Text File","Sauvegarder dans un fichier texte"}.
{"Email","Email"}.
{"Encoding for server ~b","Codage pour le serveur ~b"}.
{"End User Session","Terminer la session de l'utilisateur"}.
{"Enter the text you see","Tapez le texte que vous voyez"}.
{"Family Name","Nom de famille"}.
{"February","Février"}.
{"Friday","Vendredi"}.
{"From ~s","De ~s"}.
{"Full Name","Nom complet"}.
{"Get Number of Online Users","Récupérer le nombre d'utilisateurs en ligne"}.
{"Get Number of Registered Users","Récupérer le nombre d'utilisateurs enregistrés"}.
{"Get User Last Login Time","Récupérer la dernière date de connexion de l'utilisateur"}.
{"Get User Password","Récupérer le mot de passe de l'utilisateur"}.
{"Get User Statistics","Récupérer les statistiques de l'utilisateur"}.
{"has been banned","a été banni"}.
{"has been kicked","a été expulsé"}.
{"has been kicked because of an affiliation change","a été éjecté à cause d'un changement d'autorisation"}.
{"has been kicked because of a system shutdown","a été éjecté en raison de l'arrêt du système"}.
{"has been kicked because the room has been changed to members-only","a été éjecté car la salle est désormais réservée aux membres"}.
{" has set the subject to: "," a changé le sujet pour: "}.
{"Import Directory","Importer une répertoire"}.
{"Import File","Importer un fichier"}.
{"is now known as","est maintenant connu comme"}.
{"Jabber ID","Jabber ID"}.
{"January","Janvier"}.
{"joins the room","rejoint le salon"}.
{"July","Juillet"}.
{"June","Juin"}.
{"leaves the room","quitte le salon"}.
{"March","Mars"}.
{"May","Mai"}.
{"Middle Name","Autre nom"}.
{"Monday","Lundi"}.
{"Name","Nom"}.
{"Nickname","Pseudo"}.
{"November","Novembre"}.
{"October","Octobre"}.
{"Organization Name","Nom de l'organisation"}.
{"Organization Unit","Unité de l'organisation"}.
{"Password ~b","Mot de passe ~b"}.
{"Ping","Ping"}.
{"Port ~b","Port ~b"}.
{"private, ","privé"}.
{"Restart Service","Redémarrer le service"}.
{"Restore","Restauration"}.
{"Room Configuration","Configuration du salon"}.
{"Room Occupants","Occupants du salon"}.
{"Saturday","Samedi"}.
{"Search Results for ","Résultats de recherche pour "}.
{"September","Septembre"}.
{"Server ~b","Serveur ~b"}.
{"Shut Down Service","Arrêter le service"}.
{"Start Modules","Modules de démarrage"}.
{"Stop Modules","Modules d'arrêt"}.
{"Sunday","Dimanche"}.
{"The CAPTCHA is valid.","Le CAPTCHA est valide"}.
{"This IP address is blacklisted in ~s","Cette adresse IP est blacklistée dans ~s"}.
{"Thursday","Jeudi"}.
{"Too many (~p) failed authentications from this IP address (~s). The address will be unblocked at ~s UTC","Trop (~p) d'authentification ont échoué pour cette adresse IP (~s). L'adresse sera débloquée à ~s UTC"}.
{"To ~s","A ~s"}.
{"Tuesday","Mardi"}.
{"Wednesday","Mercredi"}.
