%% -*- coding: latin-1 -*-
{"Access Control Lists","Listas de Control de Acceso"}.
{"Access Rules","Regras de Acceso"}.
{"Add User","Engadir usuario"}.
{"April","Abril"}.
{"August","Agosto"}.
{"Backup","Copia de seguridade"}.
{"Birthday","Aniversario"}.
{"Change User Password","Cambiar contrasinal de usuario"}.
{"Chatroom configuration modified","Configuración da sala modificada"}.
{"Chatroom is created","Creouse a sala"}.
{"Chatroom is destroyed","Destruíuse a sala"}.
{"Chatroom is started","Iniciouse a sala"}.
{"Chatroom is stopped","Detívose a sala"}.
{"City","Cidade"}.
{"Configuration","Configuración"}.
{"Country","País"}.
{"Database","Base de datos"}.
{"December","Decembro"}.
{"Delete User","Borrar usuario"}.
{"Dump to Text File","Exportar a ficheiro de texto"}.
{"Email","Email"}.
{"Encoding for server ~b","Codificación de servidor ~b"}.
{"End User Session","Pechar sesión de usuario"}.
{"Enter the text you see","Introduza o texto que ves"}.
{"Family Name","Apelido"}.
{"February","Febreiro"}.
{"Friday","Venres"}.
{"From ~s","De ~s"}.
{"Full Name","Nome completo"}.
{"Get Number of Online Users","Ver número de usuarios conectados"}.
{"Get Number of Registered Users","Ver número de usuarios rexistrados"}.
{"Get User Last Login Time","Ver data da última conexión de usuario"}.
{"Get User Password","Ver contrasinal de usuario"}.
{"Get User Statistics","Ver estatísticas de usuario"}.
{"has been banned","foi bloqueado"}.
{"has been kicked because of an affiliation change","foi expulsado debido a un cambio de afiliación"}.
{"has been kicked because of a system shutdown","foi expulsado porque o sistema vaise a deter"}.
{"has been kicked because the room has been changed to members-only","foi expulsado, porque a sala cambiouse a só-membros"}.
{"has been kicked","foi expulsado"}.
{" has set the subject to: "," puxo o asunto: "}.
{"Import Directory","Importar directorio"}.
{"Import File","Importar ficheiro"}.
{"is now known as","cámbiase o nome a"}.
{"Jabber ID","Jabber ID"}.
{"January","Xaneiro"}.
{"joins the room","entra na sala"}.
{"July","Xullo"}.
{"June","Xuño"}.
{"leaves the room","sae da sala"}.
{"March","Marzo"}.
{"May","Maio"}.
{"Middle Name","Segundo nome"}.
{"Monday","Luns"}.
{"Name","Nome"}.
{"Nickname","Alcume"}.
{"November","Novembro"}.
{"October","Outubro"}.
{"Organization Name","Nome da organización"}.
{"Organization Unit","Unidade da organización"}.
{"Password ~b","Contrasinal ~b"}.
{"Ping","Ping"}.
{"Port ~b","Porto ~b"}.
{"private, ","privado"}.
{"Restart Service","Reiniciar o servizo"}.
{"Restore","Restaurar"}.
{"Room Configuration","Configuración da Sala"}.
{"Room Occupants","Ocupantes da sala"}.
{"Saturday","Sábado"}.
{"Search Results for ","Buscar resultados por "}.
{"September","Setembro"}.
{"Server ~b","Servidor ~b"}.
{"Shut Down Service","Deter o servizo"}.
{"Start Modules","Iniciar módulos"}.
{"Stop Modules","Deter módulos"}.
{"Sunday","Domingo"}.
{"The CAPTCHA is valid.","O CAPTCHA é válido."}.
{"This IP address is blacklisted in ~s","Esta dirección IP está na lista negra en ~s"}.
{"Thursday","Xoves"}.
{"Too many (~p) failed authentications from this IP address (~s). The address will be unblocked at ~s UTC","Demasiados (~p) fallou autenticaciones desde esta dirección IP (~s). A dirección será desbloqueada as ~s UTC"}.
{"To ~s","A ~s"}.
{"Tuesday","Martes"}.
{"Wednesday","Mércores"}.
