%% -*- coding: latin-1 -*-
{"Access Control Lists","רשימות בקרת גישה"}.
{"Access Rules","כללי גישה"}.
{"Add User","הוסף משתמש"}.
{"April","אפריל"}.
{"August","אוגוסט"}.
{"Backup","גיבוי"}.
{"Birthday","יום הולדת"}.
{"Change User Password","שנה סיסמת משתמש"}.
{"Chatroom configuration modified","תצורת חדר שיחה שונתה"}.
{"Chatroom is created","חדר שיחה נוצר כעת"}.
{"Chatroom is destroyed","חדר שיחה הינו הרוס"}.
{"Chatroom is started","חדר שיחה מותחל כעת"}.
{"Chatroom is stopped","חדר שיחה הינו מופסק"}.
{"City","עיר"}.
{"Configuration","תצורה"}.
{"Country","ארץ"}.
{"Database","מסד נתונים"}.
{"December","דצמבר"}.
{"Delete User","מחק משתמש"}.
{"Dump to Text File","השלך לקובץ טקסט"}.
{"Email","דוא״ל"}.
{"Encoding for server ~b","קידוד עבור שרת ~b"}.
{"End User Session","סיים סשן משתמש"}.
{"Enter the text you see","הזן את הכיתוב שאתה רואה"}.
{"Family Name","שם משפחה"}.
{"February","פברואר"}.
{"Friday","יום שישי"}.
{"From ~s","מאת ~s"}.
{"Full Name","שם מלא"}.
{"Get Number of Online Users","השג מספר של משתמשים מקוונים"}.
{"Get Number of Registered Users","השג מספר של משתמשים רשומים"}.
{"Get User Last Login Time","השג זמן כניסה אחרון של משתמש"}.
{"Get User Password","השג סיסמת משתמש"}.
{"Get User Statistics","השג סטטיסטיקת משתמש"}.
{"has been banned","נאסר/ה"}.
{"has been kicked because of an affiliation change","נבעט/ה משום שינוי סינוף"}.
{"has been kicked because of a system shutdown","נבעט/ה משום כיבוי מערכת"}.
{"has been kicked because the room has been changed to members-only","נבעט/ה משום שהחדר שונה אל חברים-בלבד"}.
{"has been kicked","נבעט/ה"}.
{" has set the subject to: "," הגדיר/ה את הנושא אל: "}.
{"Import Directory","ייבוא מדור"}.
{"Import File","ייבוא קובץ"}.
{"is now known as","ידועה כעת בכינוי"}.
{"Jabber ID","מזהה Jabber"}.
{"January","ינואר"}.
{"joins the room","נכנס/ת אל החדר"}.
{"July","יולי"}.
{"June","יוני"}.
{"leaves the room","עוזב/ת את החדר"}.
{"March","מרץ"}.
{"May","מאי"}.
{"Middle Name","שם אמצעי"}.
{"Monday","יום שני"}.
{"Name","שם"}.
{"Nickname","שם כינוי"}.
{"November","נובמבר"}.
{"October","אוקטובר"}.
{"Organization Name","שם ארגון"}.
{"Organization Unit","יחידת איגוד"}.
{"Password ~b","סיסמה ~b"}.
{"Ping","פינג"}.
{"Port ~b","פורט ~b"}.
{"private, ","פרטי, "}.
{"Restart Service","אתחל שירות"}.
{"Restore","שחזר"}.
{"Room Configuration","תצורת חדר"}.
{"Room Occupants","נוכחי חדר"}.
{"Saturday","יום שבת"}.
{"Search Results for ","תוצאות חיפוש עבור "}.
{"September","ספטמבר"}.
{"Server ~b","שרת ~b"}.
{"Shut Down Service","כבה שירות"}.
{"Start Modules","התחל מודולים"}.
{"Stop Modules","הפסק מודולים"}.
{"Sunday","יום ראשון"}.
{"The CAPTCHA is valid.","‏CAPTCHA הינה תקפה."}.
{"This IP address is blacklisted in ~s","כתובת IP זו רשומה ברשימה שחורה בתוך ~s"}.
{"Thursday","יום חמישי"}.
{"Too many (~p) failed authentications from this IP address (~s). The address will be unblocked at ~s UTC","יותר מדי (~p) אימותים כושלים מתוך כתובת IP זו (~s). הכתובת תורשה לקבל גישה בשעה ~s UTC"}.
{"To ~s","אל ~s"}.
{"Tuesday","יום שלישי"}.
{"Wednesday","יום רביעי"}.
