%% -*- coding: latin-1 -*-
{"Access Control Lists","Akses Daftar Pengendalian"}.
{"Access Rules","Aturan Akses"}.
{"Add User","Tambah Pengguna"}.
{"April","April"}.
{"August","Agustus"}.
{"Backup","Backup"}.
{"Birthday","Hari Lahir"}.
{"Change User Password","Ubah User Password"}.
{"Chatroom configuration modified","Konfigurasi ruang chat diubah"}.
{"Chatroom is created","Ruang chat telah dibuat"}.
{"Chatroom is destroyed","Ruang chat dilenyapkan"}.
{"Chatroom is started","Ruang chat dimulai"}.
{"Chatroom is stopped","Ruang chat dihentikan"}.
{"City","Kota"}.
{"Configuration","Pengaturan"}.
{"Country","Negara"}.
{"Database","Database"}.
{"December","Desember"}.
{"Delete User","Hapus Pengguna"}.
{"Dump to Text File","Dump menjadi File Teks"}.
{"Email","Email"}.
{"Encoding for server ~b","Pengkodean untuk layanan ~b"}.
{"End User Session","Akhir Sesi Pengguna"}.
{"Enter the text you see","Masukkan teks yang Anda lihat"}.
{"Family Name","Nama Keluarga (marga)"}.
{"February","Februari"}.
{"Friday","Jumat"}.
{"From ~s","Dari ~s"}.
{"Full Name","Nama Lengkap"}.
{"Get Number of Online Users","Dapatkan Jumlah User Yang Online"}.
{"Get Number of Registered Users","Dapatkan Jumlah Pengguna Yang Terdaftar"}.
{"Get User Last Login Time","Dapatkan Waktu Login Terakhir Pengguna "}.
{"Get User Password","Dapatkan User Password"}.
{"Get User Statistics","Dapatkan Statistik Pengguna"}.
{"has been banned","telah dibanned"}.
{"has been kicked because of an affiliation change","telah dikick karena perubahan afiliasi"}.
{"has been kicked because of a system shutdown","telah dikick karena sistem shutdown"}.
{"has been kicked because the room has been changed to members-only","telah dikick karena ruangan telah diubah menjadi hanya untuk member"}.
{"has been kicked","telah dikick"}.
{" has set the subject to: ","telah menetapkan topik yaitu:"}.
{"Import Directory","Impor Direktori"}.
{"Import File","Impor File"}.
{"is now known as","sekarang dikenal sebagai"}.
{"Jabber ID","Jabber ID"}.
{"January","Januari"}.
{"joins the room","bergabung ke ruangan"}.
{"July","Juli"}.
{"June","Juni"}.
{"leaves the room","meninggalkan ruangan"}.
{"March","Maret"}.
{"May","Mei"}.
{"Middle Name","Nama Tengah"}.
{"Monday","Senin"}.
{"Name","Nama"}.
{"Nickname","Nama Julukan"}.
{"November","Nopember"}.
{"October","Oktober"}.
{"Organization Name","Nama Organisasi"}.
{"Organization Unit","Unit Organisasi"}.
{"Password ~b","Kata Sandi ~b"}.
{"Ping","Ping"}.
{"Port ~b","Port ~b"}.
{"private, ","pribadi, "}.
{"Restart Service","Restart Layanan"}.
{"Restore","Mengembalikan"}.
{"Room Configuration","Konfigurasi Ruangan"}.
{"Room Occupants","Penghuni Ruangan"}.
{"Saturday","Sabtu"}.
{"Search Results for ","Hasil Pencarian untuk"}.
{"September","September"}.
{"Server ~b","Layanan ~b"}.
{"Shut Down Service","Shut Down Layanan"}.
{"Start Modules","Memulai Modul"}.
{"Stop Modules","Hentikan Modul"}.
{"Sunday","Minggu"}.
{"The CAPTCHA is valid.","Captcha ini benar."}.
{"Thursday","Kamis"}.
{"To ~s","Kepada ~s"}.
{"Tuesday","Selasa"}.
{"Wednesday","Rabu"}.
