%% -*- coding: latin-1 -*-
{"Access Control Lists","Diritti di accesso (ACL)"}.
{"Access Rules","Regole di accesso"}.
{"Add User","Aggiungere un utente"}.
{"April","Aprile"}.
{"August","Agosto"}.
{"Backup","Salvare"}.
{"Birthday","Compleanno"}.
{"Change User Password","Cambiare la password dell'utente"}.
{"Chatroom configuration modified","Configurazione della stanza modificata"}.
{"Chatroom is created","La stanza è creata"}.
{"Chatroom is destroyed","La stanza è eliminata"}.
{"Chatroom is started","La stanza è avviata"}.
{"Chatroom is stopped","La stanza è arrestata"}.
{"City","Città"}.
{"Configuration","Configurazione"}.
{"Country","Paese"}.
{"Database","Database"}.
{"December","Dicembre"}.
{"Delete User","Eliminare l'utente"}.
{"Dump to Text File","Trascrivere su file di testo"}.
{"Email","E-mail"}.
{"Encoding for server ~b","Codifica per il server ~b"}.
{"End User Session","Terminare la sessione dell'utente"}.
{"Enter the text you see","Immettere il testo visibile"}.
{"Family Name","Cognome"}.
{"February","Febbraio"}.
{"Friday","Venerdì"}.
{"From ~s","Da ~s"}.
{"Full Name","Nome completo"}.
{"Get Number of Online Users","Ottenere il numero di utenti online"}.
{"Get Number of Registered Users","Ottenere il numero di utenti registrati"}.
{"Get User Last Login Time","Ottenere la data di ultimo accesso dell'utente"}.
{"Get User Password","Ottenere la password dell'utente"}.
{"Get User Statistics","Ottenere le statistiche dell'utente"}.
{"has been banned","è stata/o bandita/o"}.
{"has been kicked because of an affiliation change","è stato espulso a causa di un cambiamento di appartenenza"}.
{"has been kicked because of a system shutdown","è stato espulso a causa dello spegnimento del sistema"}.
{"has been kicked because the room has been changed to members-only","è stato espulso per la limitazione della stanza ai soli membri"}.
{"has been kicked","è stata/o espulsa/o"}.
{" has set the subject to: "," ha modificato l'oggetto in: "}.
{"Import Directory","Importare una directory"}.
{"Import File","Importare un file"}.
{"is now known as","è ora conosciuta/o come"}.
{"Jabber ID","Jabber ID (Jabber ID)"}.
{"January","Gennaio"}.
{"joins the room","entra nella stanza"}.
{"July","Luglio"}.
{"June","Giugno"}.
{"leaves the room","esce dalla stanza"}.
{"March","Marzo"}.
{"May","Maggio"}.
{"Middle Name","Altro nome"}.
{"Monday","Lunedì"}.
{"Name","Nome"}.
{"Nickname","Nickname"}.
{"November","Novembre"}.
{"October","Ottobre"}.
{"Organization Name","Nome dell'organizzazione"}.
{"Organization Unit","Unità dell'organizzazione"}.
{"Password ~b","Password ~b"}.
{"Ping","Ping"}.
{"Port ~b","Porta ~b"}.
{"private, ","privato, "}.
{"Restart Service","Riavviare il servizio"}.
{"Restore","Recuperare"}.
{"Room Configuration","Configurazione della stanza"}.
{"Room Occupants","Presenti nella stanza"}.
{"Saturday","Sabato"}.
{"Search Results for ","Risultati della ricerca per "}.
{"September","Settembre"}.
{"Server ~b","Server ~b"}.
{"Shut Down Service","Terminare il servizio"}.
{"Start Modules","Avviare moduli"}.
{"Stop Modules","Arrestare moduli"}.
{"Sunday","Domenica"}.
{"The CAPTCHA is valid.","Il CAPTCHA è valido."}.
{"Thursday","Giovedì"}.
{"To ~s","A ~s"}.
{"Tuesday","Martedì"}.
{"Wednesday","Mercoledì"}.
