%% -*- coding: latin-1 -*-
{"Access Control Lists","アクセスコントロールリスト"}.
{"Access Rules","アクセスルール"}.
{"Add User","ユーザーを追加"}.
{"April","4月"}.
{"August","8月"}.
{"Backup","バックアップ"}.
{"Birthday","誕生日"}.
{"Change User Password","パスワードを変更"}.
{"Chatroom configuration modified","チャットルームの設定が変更されました"}.
{"Chatroom is created","チャットルームを作りました"}.
{"Chatroom is destroyed","チャットルームを終了しました"}.
{"Chatroom is started","チャットルームを開始しました"}.
{"Chatroom is stopped","チャットルームを停止しました"}.
{"City","都道府県"}.
{"Configuration","設定"}.
{"Country","国"}.
{"Database","データーベース"}.
{"December","12月"}.
{"Delete User","ユーザーを削除"}.
{"Dump to Text File","テキストファイルに出力"}.
{"Email","メールアドレス"}.
{"Encoding for server ~b","サーバーのエンコーディング ~b"}.
{"End User Session","エンドユーザーセッション"}.
{"Enter the text you see","見えているテキストを入力してください"}.
{"Family Name","姓"}.
{"February","2月"}.
{"Friday","金曜日"}.
{"From ~s","From ~s"}.
{"Full Name","氏名"}.
{"Get Number of Online Users","オンラインユーザー数を取得"}.
{"Get Number of Registered Users","登録ユーザー数を取得"}.
{"Get User Last Login Time","最終ログイン時間を取得"}.
{"Get User Password","パスワードを取得"}.
{"Get User Statistics","ユーザー統計を取得"}.
{"has been banned","はバンされました"}.
{"has been kicked","はキックされました"}.
{"has been kicked because of an affiliation change","は分掌が変更されたためキックされました"}.
{"has been kicked because of a system shutdown","はシステムシャットダウンのためキックされました"}.
{"has been kicked because the room has been changed to members-only","はチャットルームがメンバー制に変更されたためキックされました"}.
{" has set the subject to: "," は件名を設定しました: "}.
{"Import Directory","ディレクトリインポート"}.
{"Import File","ファイルからインポート"}.
{"is now known as","は名前を変更しました: "}.
{"Jabber ID","Jabber ID"}.
{"January","1月"}.
{"joins the room","がチャットルームに参加しました"}.
{"July","7月"}.
{"June","6月"}.
{"leaves the room","がチャットルームから退出しました"}.
{"March","3月"}.
{"May","5月"}.
{"Middle Name","ミドルネーム"}.
{"Monday","月曜日"}.
{"Name","名"}.
{"Nickname","ニックネーム"}.
{"November","11月"}.
{"October","10月"}.
{"Organization Name","会社名"}.
{"Organization Unit","部署名"}.
{"Password ~b","パスワード ~b"}.
{"Ping","Ping"}.
{"Port ~b","ポート ~b"}.
{"private, ","プライベート、"}.
{"Restart Service","サービスを再起動"}.
{"Restore","リストア"}.
{"Room Configuration","チャットルームの設定"}.
{"Room Occupants","在室者"}.
{"Saturday","土曜日"}.
{"Search Results for ","検索結果: "}.
{"September","9月"}.
{"Server ~b","サーバー ~b"}.
{"Shut Down Service","サービスを停止"}.
{"Start Modules","モジュールを起動"}.
{"Stop Modules","モジュールを停止"}.
{"Sunday","日曜日"}.
{"The CAPTCHA is valid.","CAPTCHA は有効です。"}.
{"This IP address is blacklisted in ~s","このIPアドレスはアクセスを禁止されています ~s"}.
{"Thursday","木曜日"}.
{"Too many (~p) failed authentications from this IP address (~s). The address will be unblocked at ~s UTC","~p回の認証に失敗しました。このIPアドレス(~s)は~s UTCまでブロックされます。"}.
{"To ~s","宛先 ~s"}.
{"Tuesday","火曜日"}.
{"Wednesday","水曜日"}.
