%% -*- coding: latin-1 -*-
{"Access Control Lists","Access control lists"}.
{"Access Rules","Access rules"}.
{"Add User","Gebruiker toevoegen"}.
{"April","April"}.
{"August","Augustus"}.
{"Backup","Backup"}.
{"Birthday","Geboortedatum"}.
{"Change User Password","Verander Gebruikerswachtwoord"}.
{"Chatroom configuration modified","De instellingen van de chatruimte werden veranderd"}.
{"Chatroom is created","Gespreksruimte gecreëerd"}.
{"Chatroom is destroyed","Gespreksruimte vernietigd"}.
{"Chatroom is started","Gespreksruimte gestart"}.
{"Chatroom is stopped","Gespreksruimte gestopt"}.
{"City","Plaats"}.
{"Configuration","Instellingen"}.
{"Country","Land"}.
{"Database","Database"}.
{"December","December"}.
{"Delete User","Verwijder Gebruiker"}.
{"Dump to Text File","Backup naar een tekstbestand schrijven"}.
{"Email","E-mail"}.
{"Encoding for server ~b","Karakterset voor server ~b"}.
{"End User Session","Verwijder Gebruikers-sessie"}.
{"Enter the text you see","Voer de getoonde tekst in"}.
{"Family Name","Achternaam"}.
{"February","Februari"}.
{"Friday","Vrijdag"}.
{"From ~s","Van ~s"}.
{"Full Name","Volledige naam"}.
{"Get Number of Online Users","Aantal Aanwezige Gebruikers Opvragen"}.
{"Get Number of Registered Users","Aantal Geregistreerde Gebruikers Opvragen"}.
{"Get User Last Login Time","Tijd van Laatste Aanmelding Opvragen"}.
{"Get User Password","Gebruikerswachtwoord Opvragen"}.
{"Get User Statistics","Gebruikers-statistieken Opvragen"}.
{"has been banned","is verbannen"}.
{"has been kicked because of an affiliation change","is weggestuurd vanwege een affiliatieverandering"}.
{"has been kicked because of a system shutdown","is weggestuurd omdat het systeem gestopt wordt"}.
{"has been kicked because the room has been changed to members-only","is weggestuurd omdat de chatruimte vanaf heden alleen toegankelijk is voor leden"}.
{"has been kicked","is weggestuurd"}.
{" has set the subject to: "," veranderde het onderwerp in: "}.
{"Import Directory","Directory importeren"}.
{"Import File","Bestand importeren"}.
{"is now known as","heet nu"}.
{"Jabber ID","Jabber ID"}.
{"January","Januari"}.
{"joins the room","betrad de chatruimte"}.
{"July","Juli"}.
{"June","Juni"}.
{"leaves the room","verliet de chatruimte"}.
{"March","Maart"}.
{"May","Mei"}.
{"Middle Name","Tussennaam"}.
{"Monday","Maandag"}.
{"Name","Naam"}.
{"Nickname","Bijnaam"}.
{"November","November"}.
{"October","Oktober"}.
{"Organization Name","Organisatie"}.
{"Organization Unit","Afdeling"}.
{"Password ~b","Wachtwoord ~b"}.
{"Ping","Ping"}.
{"Port ~b","Poort ~b"}.
{"private, ","privé, "}.
{"Restart Service","Herstart Service"}.
{"Restore","Binaire backup direct herstellen"}.
{"Room Configuration","Instellingen van de chatruimte"}.
{"Room Occupants","Aantal aanwezigen"}.
{"Saturday","Zaterdag"}.
{"Search Results for ","Zoekresultaten voor "}.
{"September","September"}.
{"Server ~b","Server ~b"}.
{"Shut Down Service","Stop Service"}.
{"Start Modules","Modules starten"}.
{"Stop Modules","Modules stoppen"}.
{"Sunday","Zondag"}.
{"The CAPTCHA is valid.","De geautomatiseerde Turing-test is geslaagd."}.
{"This IP address is blacklisted in ~s","Dit IP-adres is geblokkeerd in ~s"}.
{"Thursday","Donderdag"}.
{"Too many (~p) failed authentications from this IP address (~s). The address will be unblocked at ~s UTC","Te veel (~p) mislukte authenticatie-pogingen van dit IP-adres (~s). Dit adres zal worden gedeblokkeerd om ~s UTC"}.
{"To ~s","Naar ~s"}.
{"Tuesday","Dinsdag"}.
{"Wednesday","Woensdag"}.
