%% -*- coding: latin-1 -*-
{"Access Control Lists","Tilgangskontrollister"}.
{"Access Rules","Tilgangsregler"}.
{"Add User","Legg til Bruker"}.
{"April","april"}.
{"August","august"}.
{"Backup","Sikkerhetskopier"}.
{"Birthday","Fødselsdag"}.
{"Change User Password","Endre Brukers Passord"}.
{"Chatroom configuration modified","Samtalerommets konfigurasjon er endret"}.
{"Chatroom is created","Samtalerom er opprettet"}.
{"Chatroom is destroyed","Samtalerom er fjernet"}.
{"Chatroom is started","Samtalerom er startet"}.
{"Chatroom is stopped","Samtalerom er stoppet"}.
{"City","By"}.
{"Configuration","Konfigurasjon"}.
{"Country","Land"}.
{"Database","Database"}.
{"December","desember"}.
{"Delete User","Slett Bruker"}.
{"Dump to Text File","Dump til Tekstfil"}.
{"Email","Epost"}.
{"Encoding for server ~b","Tekstkoding for server ~b"}.
{"End User Session","Avslutt Bruker Sesjon"}.
{"Enter the text you see","Skriv inn teksten du ser"}.
{"Family Name","Etternavn"}.
{"February","februar"}.
{"Friday","fredag"}.
{"From ~s","Fra ~s"}.
{"Full Name","Fullstendig Navn"}.
{"Get Number of Online Users","Vis Antall Tilkoblede Brukere"}.
{"Get Number of Registered Users","Vis Antall Registrerte Brukere"}.
{"Get User Last Login Time","Vis Brukers Siste Påloggings Tidspunkt"}.
{"Get User Password","Hent Brukers Passord"}.
{"Get User Statistics","Vis Bruker Statistikk"}.
{"has been banned","har blitt bannlyst"}.
{"has been kicked because of an affiliation change","har blitt kastet ut på grunn av en tilknytnings endring"}.
{"has been kicked because of a system shutdown","har blitt kastet ut på grunn av at systemet avslutter"}.
{"has been kicked because the room has been changed to members-only","har blitt kastet ut på grunn av at rommet er endret til kun-for-medlemmer"}.
{"has been kicked","har blitt kastet ut"}.
{" has set the subject to: "," har satt emnet til: "}.
{"Import Directory","Importer Katalog"}.
{"Import File","Importer File"}.
{"is now known as","er nå kjent som"}.
{"Jabber ID","Jabber ID"}.
{"January","januar"}.
{"joins the room","kommer inn i rommet"}.
{"July","juli"}.
{"June","juni"}.
{"leaves the room","forlater rommet"}.
{"March","mars"}.
{"May","mai"}.
{"Middle Name","Mellomnavn"}.
{"Monday","mandag"}.
{"Name","Navn"}.
{"Nickname","Kallenavn"}.
{"November","november"}.
{"October","oktober"}.
{"Organization Name","Organisasjonsnavn"}.
{"Organization Unit","Organisasjonsenhet"}.
{"Password ~b","Passord ~b"}.
{"Ping","Ping"}.
{"Port ~b","Port ~b"}.
{"private, ","privat, "}.
{"Restart Service","Start Tjeneste på Nytt"}.
{"Restore","Gjenopprett"}.
{"Room Configuration","Rom Konfigurasjon"}.
{"Room Occupants","Samtalerom Deltakere"}.
{"Saturday","lørdag"}.
{"Search Results for ","Søke Resultater for "}.
{"September","september"}.
{"Server ~b","Server ~b"}.
{"Shut Down Service","Avslutt Tjeneste"}.
{"Start Modules","Start Moduler"}.
{"Stop Modules","Stop Moduler"}.
{"Sunday","søndag"}.
{"The CAPTCHA is valid.","Captchaen er ikke gyldig"}.
{"Thursday","torsdag"}.
{"To ~s","Til ~s"}.
{"Tuesday","tirsdag"}.
{"Wednesday","onsdag"}.
