%% -*- coding: latin-1 -*-
{"Access Control Lists","Lista dostępowa"}.
{"Access Rules","Zasady dostępu"}.
{"Add User","Dodaj użytkownika"}.
{"April","Kwiecień"}.
{"August","Sierpień"}.
{"Backup","Wykonaj kopie"}.
{"Birthday","Data urodzenia"}.
{"Change User Password","Zmień hasło użytkownika"}.
{"Chatroom configuration modified","Konfiguracja pokoju zmodyfikowana"}.
{"Chatroom is created","Pokój został stworzony"}.
{"Chatroom is destroyed","Pokój został usunięty"}.
{"Chatroom is started","Pokój został uruchomiony"}.
{"Chatroom is stopped","Pokój został zatrzymany"}.
{"City","Miasto"}.
{"Configuration","Konfiguracja"}.
{"Country","Państwo"}.
{"Database","Baza danych"}.
{"December","Grudzień"}.
{"Delete User","Usuń użytkownika"}.
{"Dump to Text File","Wykonaj kopie do pliku tekstowego"}.
{"Email","Email"}.
{"Encoding for server ~b","Kodowanie znaków dla serwera ~b"}.
{"End User Session","Zakończ sesję uzytkownika"}.
{"Enter the text you see","Przepisz tekst z obrazka"}.
{"Family Name","Nazwisko"}.
{"February","Luty"}.
{"Friday","Piątek"}.
{"From ~s","Od ~s"}.
{"Full Name","Pełna nazwa"}.
{"Get Number of Online Users","Pokaż liczbę zalogowanych użytkowników"}.
{"Get Number of Registered Users","Pokaż liczbę zarejestrowanych użytkowników"}.
{"Get User Last Login Time","Pokaż czas ostatniego zalogowania uzytkownika"}.
{"Get User Password","Pobierz hasło użytkownika"}.
{"Get User Statistics","Pobierz statystyki użytkownika"}.
{"has been banned","został wykluczony"}.
{"has been kicked because of an affiliation change","został wyrzucony z powodu zmiany przynależności"}.
{"has been kicked because of a system shutdown","został wyrzucony z powodu wyłączenia systemu"}.
{"has been kicked because the room has been changed to members-only","został wyrzucony z powodu zmiany pokoju na \"Tylko dla Członków\""}.
{"has been kicked","został wyrzucony"}.
{" has set the subject to: "," zmienił temat na: "}.
{"Import Directory","Importuj katalog"}.
{"Import File","Importuj plik"}.
{"is now known as","jest teraz znany jako"}.
{"Jabber ID","Jabber ID"}.
{"January","Styczeń"}.
{"joins the room","dołącza do pokoju"}.
{"July","Lipiec"}.
{"June","Czerwiec"}.
{"leaves the room","opuszcza pokój"}.
{"March","Marzec"}.
{"May","Maj"}.
{"Middle Name","Drugie imię"}.
{"Monday","Poniedziałek"}.
{"Name","Imię"}.
{"Nickname","Nazwa użytkownika"}.
{"November","Listopad"}.
{"October","Październik"}.
{"Organization Name","Nazwa organizacji"}.
{"Organization Unit","Dział"}.
{"Password ~b","Hasło ~b"}.
{"Ping","Ping"}.
{"Port ~b","Port ~b"}.
{"private, ","prywatny, "}.
{"Restart Service","Restart usługi"}.
{"Restore","Przywróć z kopii"}.
{"Room Configuration","Konfiguracja pokoju"}.
{"Room Occupants","Lista uczestników"}.
{"Saturday","Sobota"}.
{"Search Results for ","Wyniki wyszukiwania dla "}.
{"September","Wrzesień"}.
{"Server ~b","Serwer ~b"}.
{"Shut Down Service","Wyłącz usługę"}.
{"Start Modules","Uruchom moduły"}.
{"Stop Modules","Zatrzymaj moduły"}.
{"Sunday","Niedziela"}.
{"The CAPTCHA is valid.","Captcha jest poprawna."}.
{"This IP address is blacklisted in ~s","Ten adres IP został zablokowany w ~s"}.
{"Thursday","Czwartek"}.
{"Too many (~p) failed authentications from this IP address (~s). The address will be unblocked at ~s UTC","Zbyt wiele (~p) nieudanych prób logowanie z tego adresu IP (~s). Ten adres zostanie odblokowany o ~s UTC"}.
{"To ~s","Do ~s"}.
{"Tuesday","Wtorek"}.
{"Wednesday","Środa"}.
