%% -*- coding: latin-1 -*-
{"Access Control Lists","Listas de Controle de Acesso"}.
{"Access Rules","Regras de Acesso"}.
{"Add User","Adicionar usuário"}.
{"April","Abril"}.
{"August","Agosto"}.
{"Backup","Salvar cópia de segurança"}.
{"Birthday","Aniversário"}.
{"Change User Password","Alterar Senha do Usuário"}.
{"Chatroom configuration modified","Configuração da sala de bate-papo modificada"}.
{"Chatroom is created","A sala de chat está criada"}.
{"Chatroom is destroyed","A sala de chat está destruída"}.
{"Chatroom is started","A sala de chat está iniciada"}.
{"Chatroom is stopped","A sala de chat está parada"}.
{"City","Cidade"}.
{"Configuration","Configuração"}.
{"Country","País"}.
{"Database","Base de dados"}.
{"December","Dezembro"}.
{"Delete User","Deletar Usuário"}.
{"Dump to Text File","Exportar para arquivo texto"}.
{"Email","Email"}.
{"Encoding for server ~b","Codificação para o servidor ~b"}.
{"End User Session","Terminar Sessão do Usuário"}.
{"Enter the text you see","Insira o texto que você vê"}.
{"Family Name","Sobrenome"}.
{"February","Fevereiro"}.
{"Friday","Sexta"}.
{"From ~s","De ~s"}.
{"Full Name","Nome completo"}.
{"Get Number of Online Users","Obter Número de Usuários Online"}.
{"Get Number of Registered Users","Obter Número de Usuários Registrados"}.
{"Get User Last Login Time","Obter a Data do Último Login"}.
{"Get User Password","Obter Senha do Usuário"}.
{"Get User Statistics","Obter Estatísticas do Usuário"}.
{"has been banned","foi banido"}.
{"has been kicked because of an affiliation change","foi desconectado porque por afiliação inválida"}.
{"has been kicked because of a system shutdown","foi desconectado porque o sistema foi desligado"}.
{"has been kicked because the room has been changed to members-only","foi desconectado porque a política da sala mudou, só membros são permitidos"}.
{"has been kicked","foi removido"}.
{" has set the subject to: "," mudou o assunto para: "}.
{"Import Directory","Importar diretório"}.
{"Import File","Importar arquivo"}.
{"is now known as","é agora conhecido como"}.
{"Jabber ID","ID Jabber"}.
{"January","Janeiro"}.
{"joins the room","Entrar na sala"}.
{"July","Julho"}.
{"June","Junho"}.
{"leaves the room","Sair da sala"}.
{"March","Março"}.
{"May","Maio"}.
{"Middle Name","Nome do meio"}.
{"Monday","Segunda"}.
{"Name","Nome"}.
{"Nickname","Apelido"}.
{"November","Novembro"}.
{"October","Outubro"}.
{"Organization Name","Nome da organização"}.
{"Organization Unit","Departamento/Unidade"}.
{"Password ~b","Senha ~b"}.
{"Ping","Ping"}.
{"Port ~b","Porta ~b"}.
{"private, ","privado, "}.
{"Restart Service","Reiniciar Serviço"}.
{"Restore","Restaurar"}.
{"Room Configuration","Configuração de salas"}.
{"Room Occupants","Número de participantes"}.
{"Saturday","Sábado"}.
{"Search Results for ","Resultados de pesquisa para "}.
{"September","Setembro"}.
{"Server ~b","Servidor ~b"}.
{"Shut Down Service","Parar Serviço"}.
{"Start Modules","Iniciar módulos"}.
{"Stop Modules","Parar módulos"}.
{"Sunday","Domingo"}.
{"The CAPTCHA is valid.","O CAPTCHA é inválido."}.
{"This IP address is blacklisted in ~s","Este endereço IP está bloqueado em ~s"}.
{"Thursday","Quinta"}.
{"Too many (~p) failed authentications from this IP address (~s). The address will be unblocked at ~s UTC","Número excessivo (~p) de tentativas falhas de autenticação (~s). O endereço será desbloqueado às ~s UTC"}.
{"To ~s","Para ~s"}.
{"Tuesday","Terça"}.
{"Wednesday","Quarta"}.
