%% -*- coding: latin-1 -*-
{"Access Control Lists","Listas de Controlo de Acesso"}.
{"Access Rules","Regras de Acesso"}.
{"Add User","Adicionar utilizador"}.
{"Backup","Guardar cópia de segurança"}.
{"Birthday","Data de nascimento"}.
{"City","Cidade"}.
{"Configuration","Configuração"}.
{"Country","País"}.
{"Dump to Text File","Exportar para ficheiro de texto"}.
{"Family Name","Apelido"}.
{"From ~s","De ~s"}.
{"Full Name","Nome completo"}.
{" has set the subject to: "," colocou o tópico: "}.
{"Import Directory","Importar directório"}.
{"Import File","Importar ficheiro"}.
{"Middle Name","Segundo nome"}.
{"Name","Nome"}.
{"Nickname","Alcunha"}.
{"Organization Name","Nome da organização"}.
{"Organization Unit","Unidade da organização"}.
{"private, ","privado"}.
{"Restore","Restaurar"}.
{"Start Modules","Iniciar módulos"}.
{"Stop Modules","Parar módulos"}.
{"To ~s","A ~s"}.
