%% -*- coding: latin-1 -*-
{"Access Control Lists","Списки управления доступом"}.
{"Access Rules","Правила доступа"}.
{"Add User","Добавить пользователя"}.
{"April","апреля"}.
{"August","августа"}.
{"Backup","Резервное копирование"}.
{"Birthday","День рождения"}.
{"Change User Password","Изменить пароль пользователя"}.
{"Chatroom configuration modified","Конфигурация комнаты изменилась"}.
{"Chatroom is created","Комната создана"}.
{"Chatroom is destroyed","Комната уничтожена"}.
{"Chatroom is started","Комната запущена"}.
{"Chatroom is stopped","Комната остановлена"}.
{"City","Город"}.
{"Configuration","Конфигурация"}.
{"Country","Страна"}.
{"Database","База данных"}.
{"December","декабря"}.
{"Delete User","Удалить пользователя"}.
{"Dump to Text File","Копирование в текстовый файл"}.
{"Email","Электронная почта"}.
{"Encoding for server ~b","Кодировка сервера ~b"}.
{"End User Session","Завершить сеанс пользователя"}.
{"Enter the text you see","Введите увиденный текст"}.
{"Family Name","Фамилия"}.
{"February","февраля"}.
{"Friday","Пятница"}.
{"From ~s","От ~s"}.
{"Full Name","Полное имя"}.
{"Get Number of Online Users","Получить количество подключённых пользователей"}.
{"Get Number of Registered Users","Получить количество зарегистрированных пользователей"}.
{"Get User Last Login Time","Получить время последнего подключения пользователя"}.
{"Get User Password","Получить пароль пользователя"}.
{"Get User Statistics","Получить статистику по пользователю"}.
{"has been banned","запретили входить в комнату"}.
{"has been kicked because of an affiliation change","выгнали из комнаты вследствие смены ранга"}.
{"has been kicked because of a system shutdown","выгнали из комнаты из-за останова системы"}.
{"has been kicked because the room has been changed to members-only","выгнали из комнаты потому что она стала только для членов"}.
{"has been kicked","выгнали из комнаты"}.
{" has set the subject to: "," установил(а) тему: "}.
{"Import Directory","Импорт из директории"}.
{"Import File","Импорт из файла"}.
{"is now known as","изменил(а) имя на"}.
{"Jabber ID","Jabber ID"}.
{"January","января"}.
{"joins the room","вошёл(а) в комнату"}.
{"July","июля"}.
{"June","июня"}.
{"leaves the room","вышел(а) из комнаты"}.
{"March","марта"}.
{"May","мая"}.
{"Middle Name","Отчество"}.
{"Monday","Понедельник"}.
{"Name","Название"}.
{"Nickname","Псевдоним"}.
{"November","ноября"}.
{"October","октября"}.
{"Organization Name","Название организации"}.
{"Organization Unit","Отдел организации"}.
{"Password ~b","Пароль ~b"}.
{"Ping","Пинг"}.
{"Port ~b","Порт ~b"}.
{"private, ","приватная, "}.
{"Restart Service","Перезапустить службу"}.
{"Restore","Восстановление из резервной копии"}.
{"Room Configuration","Конфигурация комнаты"}.
{"Room Occupants","Участники комнаты"}.
{"Saturday","Суббота"}.
{"Search Results for ","Результаты поиска в "}.
{"September","сентября"}.
{"Server ~b","Сервер ~b"}.
{"Shut Down Service","Остановить службу"}.
{"Start Modules","Запуск модулей"}.
{"Stop Modules","Остановка модулей"}.
{"Sunday","Воскресенье"}.
{"The CAPTCHA is valid.","Проверка капчи прошла успешно."}.
{"This IP address is blacklisted in ~s","Этот IP адрес находится в чёрном списке ~s"}.
{"Thursday","Четверг"}.
{"Too many (~p) failed authentications from this IP address (~s). The address will be unblocked at ~s UTC","Слишком много (~p) неудачных попыток аутентификации с этого IP-адреса (~s). Адрес будет разблокирован в ~s UTC"}.
{"To ~s","К ~s"}.
{"Tuesday","Вторник"}.
{"Wednesday","Среда"}.
