%% -*- coding: latin-1 -*-
{"Access Control Lists","Zoznamy prístupových oprávnení (ACL)"}.
{"Access Rules","Prístupové pravidlá"}.
{"Add User","Pridať používateľa"}.
{"April","Apríl"}.
{"August","August"}.
{"Backup","Zálohovať"}.
{"Birthday","Dátum narodenia"}.
{"Change User Password","Zmeniť heslo užívateľa"}.
{"Chatroom configuration modified","Nastavenie diskusnej miestnosti bolo zmenené"}.
{"Chatroom is created","Diskusná miestnosť je vytvorená"}.
{"Chatroom is destroyed","Diskusná miestnosť je zrušená"}.
{"Chatroom is started","Diskusná miestnosť je obnovená"}.
{"Chatroom is stopped","Diskusná miestnosť je pozastavená"}.
{"City","Mesto"}.
{"Configuration","Konfigurácia"}.
{"Country","Krajina"}.
{"Database","Databáza"}.
{"December","December"}.
{"Delete User","Vymazať užívateľa"}.
{"Dump to Text File","Uložiť do textového súboru"}.
{"Email","E-mail"}.
{"Encoding for server ~b","Kódovanie pre server ~b"}.
{"End User Session","Ukončiť reláciu užívateľa"}.
{"Enter the text you see","Zadajte zobrazený text"}.
{"Family Name","Priezvisko"}.
{"February","Február"}.
{"Friday","Piatok"}.
{"From ~s","Od ~s"}.
{"Full Name","Celé meno: "}.
{"Get Number of Online Users","Zobraziť počet pripojených užívateľov"}.
{"Get Number of Registered Users","Zobraziť počet registrovaných užívateľov"}.
{"Get User Last Login Time","Zobraziť čas posledného prihlásenia"}.
{"Get User Password","Zobraziť heslo užívateľa"}.
{"Get User Statistics","Zobraziť štatistiku užívateľa"}.
{"has been banned","bol(a) zablokovaný(á)"}.
{"has been kicked because of an affiliation change","bol vyhodený(á) kvôli zmene priradenia"}.
{"has been kicked because of a system shutdown","bol vyhodený(á) kvôli reštartu systému"}.
{"has been kicked because the room has been changed to members-only","bol vyhodený(á), pretože miestnosť bola vyhradená len pre členov"}.
{"has been kicked","bol(a) vyhodený(á) z miestnosti"}.
{" has set the subject to: ","zmenil(a) tému na: "}.
{"Import Directory","Import adresára"}.
{"Import File","Import súboru"}.
{"is now known as","sa premenoval(a) na"}.
{"Jabber ID","Jabber ID"}.
{"January","Január"}.
{"joins the room","vstúpil(a) do miestnosti"}.
{"July","Júl"}.
{"June","Jún"}.
{"leaves the room","odišiel(a) z miestnosti"}.
{"March","Marec"}.
{"May","Máj"}.
{"Middle Name","Prostredné meno: "}.
{"Monday","Pondelok"}.
{"Name","Meno"}.
{"Nickname","Prezývka"}.
{"November","November"}.
{"October","Október"}.
{"Organization Name","Meno organizácie: "}.
{"Organization Unit","Organizačná jednotka: "}.
{"Password ~b","Heslo ~b"}.
{"Ping","Ping"}.
{"Port ~b","Port ~b"}.
{"private, ","súkromná, "}.
{"Restart Service","Reštartovať službu"}.
{"Restore","Obnoviť"}.
{"Room Configuration","Nastavenia miestnosti"}.
{"Room Occupants","Ľudí v miestnosti"}.
{"Saturday","Sobota"}.
{"Search Results for ","Hľadať výsledky pre "}.
{"September","September"}.
{"Server ~b","Server ~b"}.
{"Shut Down Service","Vypnúť službu"}.
{"Start Modules","Spustiť moduly"}.
{"Stop Modules","Zastaviť moduly"}.
{"Sunday","Nedeľa"}.
{"The CAPTCHA is valid.","Platná CAPTCHA."}.
{"Thursday","Štvrtok"}.
{"To ~s","Pre ~s"}.
{"Tuesday","Utorok"}.
{"Wednesday","Streda"}.
