%% -*- coding: latin-1 -*-
{"Access Control Lists","ACL"}.
{"Access Rules","Åtkomstregler"}.
{"Add User","Lägg till användare"}.
{"April","April"}.
{"August","Augusti"}.
{"Backup","Säkerhetskopiera"}.
{"Birthday","Födelsedag"}.
{"Change User Password","Andra användarlösenord"}.
{"Chatroom configuration modified","Chattrum konfiguration modifierad"}.
{"City","Stad"}.
{"Configuration","Konfiguration"}.
{"Country","Land"}.
{"Database","Databas"}.
{"December","December"}.
{"Delete User","Ta bort användare"}.
{"Dump to Text File","Dumpa till textfil"}.
{"Email","Email"}.
{"Encoding for server ~b","Encoding för server ~b"}.
{"End User Session","Avsluta användarsession"}.
{"Enter the text you see","Skriv in sökväg till textfil"}.
{"Family Name","Efternamn"}.
{"February","Februari"}.
{"Friday","Fredag"}.
{"From ~s","Från ~s"}.
{"Full Name","Fullständigt namn"}.
{"Get Number of Online Users","Hämta antal inloggade användare"}.
{"Get Number of Registered Users","Hämta antal registrerade användare"}.
{"Get User Last Login Time","Hämta användarens senast inloggade tid"}.
{"Get User Password","Hämta användarlösenord"}.
{"Get User Statistics","Hämta användarstatistik"}.
{"has been banned","har blivit bannad"}.
{"has been kicked because of an affiliation change","har blivit kickad p.g.a en ändring av tillhörighet"}.
{"has been kicked because of a system shutdown","har blivit kickad p.g.a en systemnerstängning"}.
{"has been kicked because the room has been changed to members-only","har blivit kickad p.g.a att rummet har ändrats till endast användare"}.
{"has been kicked","har blivit kickad"}.
{" has set the subject to: "," har satt ämnet till: "}.
{"Import Directory","Importera katalog"}.
{"Import File","Importera fil"}.
{"is now known as","är känd som"}.
{"Jabber ID","Jabber ID"}.
{"January","Januari"}.
{"joins the room","joinar rummet"}.
{"July","Juli"}.
{"June","Juni"}.
{"leaves the room","lämnar rummet"}.
{"March","Mars"}.
{"May","Maj"}.
{"Middle Name","Mellannamn"}.
{"Monday","Måndag"}.
{"Name","Namn"}.
{"Nickname","Smeknamn"}.
{"November","November"}.
{"October","Oktober"}.
{"Organization Name","Organisationsnamn"}.
{"Organization Unit","Organisationsenhet"}.
{"Password ~b","Lösenord ~b"}.
{"Ping","Ping"}.
{"Port ~b","Port ~b"}.
{"private, ","privat, "}.
{"Restart Service","Starta om servicen"}.
{"Restore","Återställ"}.
{"Room Configuration","Rumkonfiguration"}.
{"Room Occupants","Antal besökare"}.
{"Saturday","Lördag"}.
{"Search Results for ","Sökresultat för"}.
{"September","September"}.
{"Server ~b","Server ~b"}.
{"Shut Down Service","Stäng ner servicen"}.
{"Start Modules","Starta moduler"}.
{"Stop Modules","Stanna moduler"}.
{"Sunday","Söndag"}.
{"The CAPTCHA is valid.","Din CAPTCHA är godkänd."}.
{"Thursday","Torsdag"}.
{"To ~s","Till ~s"}.
{"Tuesday","Tisdag"}.
{"Wednesday","Onsdag"}.
