%% -*- coding: latin-1 -*-
{"Access Control Lists","รายการควบคุมการเข้าถึง"}.
{"Access Rules","กฎการเข้าถึง"}.
{"Add User","เพิ่มผู้ใช้"}.
{"April","เมษายน"}.
{"August","สิงหาคม"}.
{"Backup","การสำรองข้อมูล "}.
{"Birthday","วันเกิด"}.
{"Change User Password","เปลี่ยนรหัสผ่านของผู้ใช้"}.
{"Chatroom configuration modified","มีการปรับเปลี่ยนการกำหนดค่าของห้องสนทนา"}.
{"City","เมือง"}.
{"Configuration","การกำหนดค่า"}.
{"Country","ประเทศ"}.
{"Database","ฐานข้อมูล"}.
{"December","ธันวาคม"}.
{"Delete User","ลบผู้ใช้"}.
{"Dump to Text File","ถ่ายโอนข้อมูลไปยังไฟล์ข้อความ"}.
{"Email","อีเมล"}.
{"End User Session","สิ้นสุดเซสชันของผู้ใช้"}.
{"Family Name","นามสกุล"}.
{"February","กุมภาพันธ์"}.
{"Friday","วันศุกร์"}.
{"From ~s","จาก ~s"}.
{"Full Name","ชื่อเต็ม"}.
{"Get Number of Online Users","แสดงจำนวนผู้ใช้ออนไลน์"}.
{"Get Number of Registered Users","แสดงจำนวนผู้ใช้ที่ลงทะเบียน"}.
{"Get User Last Login Time","แสดงเวลาเข้าสู่ระบบครั้งล่าสุดของผู้ใช้"}.
{"Get User Password","ขอรับรหัสผ่านของผู้ใช้"}.
{"Get User Statistics","แสดงสถิติของผู้ใช้"}.
{"has been banned","ถูกสั่งห้าม"}.
{"has been kicked","ถูกไล่ออก"}.
{" has set the subject to: "," ตั้งหัวข้อว่า: "}.
{"Import Directory","อิมพอร์ตไดเร็กทอรี"}.
{"Import File","อิมพอร์ตไฟล์"}.
{"is now known as","ซึ่งรู้จักกันในชื่อ"}.
{"Jabber ID","Jabber ID"}.
{"January","มกราคม"}.
{"joins the room","เข้าห้องสนทนานี้"}.
{"July","กรกฎาคม"}.
{"June","มิถุนายน"}.
{"leaves the room","ออกจากห้อง"}.
{"March","มีนาคม"}.
{"May","พฤษภาคม"}.
{"Middle Name","ชื่อกลาง"}.
{"Monday","วันจันทร์"}.
{"Name","ชื่อ"}.
{"Nickname","ชื่อเล่น"}.
{"November","พฤศจิกายน"}.
{"October","ตุลาคม"}.
{"Organization Name","ชื่อองค์กร"}.
{"Organization Unit","หน่วยขององค์กร"}.
{"Ping","Ping"}.
{"private, ","ส่วนตัว, "}.
{"Restart Service","เริ่มต้นการบริการใหม่อีกครั้ง"}.
{"Restore","การคืนค่า"}.
{"Room Configuration","การกำหนดค่าห้องสนทนา"}.
{"Saturday","วันเสาร์"}.
{"Search Results for ","ผลการค้นหาสำหรับ "}.
{"September","กันยายน"}.
{"Shut Down Service","ปิดการบริการ"}.
{"Start Modules","เริ่มโมดูล"}.
{"Stop Modules","หยุดโมดูล"}.
{"Sunday","วันอาทิตย์"}.
{"Thursday","วันพฤหัสบดี"}.
{"To ~s","ถึง ~s"}.
{"Tuesday","วันอังคาร"}.
{"Wednesday","วันพุธ"}.
