%% -*- coding: latin-1 -*-
{"Access Control Lists","Erişim Kontrol Listeleri (ACL)"}.
{"Access Rules","Erişim Kuralları"}.
{"Add User","Kullanıcı Ekle"}.
{"April","Nisan"}.
{"August","Ağustos"}.
{"Backup","Yedekle"}.
{"Birthday","Doğumgünü"}.
{"Change User Password","Kullanıcı Parolasını Değiştir"}.
{"Chatroom configuration modified","Sohbet odası ayarı değiştirildi"}.
{"Chatroom is created","Sohbet odası oluşturuldu"}.
{"Chatroom is destroyed","Sohbet odası kaldırıldı"}.
{"Chatroom is started","Sohbet odası başlatıldı"}.
{"Chatroom is stopped","Sohbet odası durduruldu"}.
{"City","İl"}.
{"Configuration","Ayarlar"}.
{"Country","Ülke"}.
{"Database","Veritabanı"}.
{"December","Aralık"}.
{"Delete User","Kullanıcıyı Sil"}.
{"Dump to Text File","Metin Dosyasına Döküm Al"}.
{"Email","E-posta"}.
{"Encoding for server ~b","Sunucu için kodlama ~b"}.
{"End User Session","Kullanıcı Oturumunu Kapat"}.
{"Enter the text you see","Gördüğünüz metni giriniz"}.
{"Family Name","Soyisim"}.
{"February","Şubat"}.
{"Friday","Cuma"}.
{"From ~s","Kimden ~s"}.
{"Full Name","Tam İsim"}.
{"Get Number of Online Users","Bağlı Kullanıcı Sayısını Al"}.
{"Get Number of Registered Users","Kayıtlı Kullanıcı Sayısını Al"}.
{"Get User Last Login Time","Kullanıcı Son Giriş Zamanınlarını Al"}.
{"Get User Password","Kullanıcı Parolasını Al"}.
{"Get User Statistics","Kullanıcı İstatistiklerini Al"}.
{"has been banned","odaya girmesi yasaklandı"}.
{"has been kicked because of an affiliation change","ilişki değişikliğinden dolayı atıldı"}.
{"has been kicked because of a system shutdown","sistem kapandığından dolayı atıldı"}.
{"has been kicked because the room has been changed to members-only","oda üyelere-özel hale getirildiğinden dolayı atıldı"}.
{"has been kicked","odadan atıldı"}.
{" has set the subject to: "," konuyu değiştirdi: "}.
{"Import Directory","Dizini İçe Aktar"}.
{"Import File","Dosyayı İçe Aktar"}.
{"is now known as","isim değiştirdi :"}.
{"Jabber ID","Jabber ID"}.
{"January","Ocak"}.
{"joins the room","odaya katıldı"}.
{"July","Temmuz"}.
{"June","Haziran"}.
{"leaves the room","odadan ayrıldı"}.
{"March","Mart"}.
{"May","Mayıs"}.
{"Middle Name","Ortanca İsim"}.
{"Monday","Pazartesi"}.
{"Name","İsim"}.
{"Nickname","Takma isim"}.
{"November","Kasım"}.
{"October","Ekim"}.
{"Organization Name","Kurum İsmi"}.
{"Organization Unit","Kurumun İlgili Birimi"}.
{"Password ~b","Parola ~b"}.
{"Ping","Ping"}.
{"Port ~b","Kapı (Port) ~b"}.
{"private, ","özel"}.
{"Restart Service","Servisi Tekrar Başlat"}.
{"Restore","Yedekten Geri Al"}.
{"Room Configuration","Oda Ayarları"}.
{"Room Occupants","Oda Sakini Sayısı"}.
{"Saturday","Cumartesi"}.
{"Search Results for ","Arama sonuçları : "}.
{"September","Eylül"}.
{"Server ~b","Sunucu ~b"}.
{"Shut Down Service","Servisi Kapat"}.
{"Start Modules","Modülleri Başlat"}.
{"Stop Modules","Modülleri Durdur"}.
{"Sunday","Pazar"}.
{"The CAPTCHA is valid.","İnsan doğrulaması (captcha) geçerli."}.
{"Thursday","Perşembe"}.
{"To ~s","Kime ~s"}.
{"Tuesday","Salı"}.
{"Wednesday","Çarşamba"}.
