%% -*- coding: latin-1 -*-
{"Access Control Lists","Списки керування доступом"}.
{"Access Rules","Правила доступу"}.
{"Add User","Додати користувача"}.
{"April","квітня"}.
{"August","серпня"}.
{"Backup","Резервне копіювання"}.
{"Birthday","День народження"}.
{"Change User Password","Змінити Пароль Користувача"}.
{"Chatroom configuration modified","Конфігурація кімнати змінилась"}.
{"Chatroom is created","Створено кімнату"}.
{"Chatroom is destroyed","Знищено кімнату"}.
{"Chatroom is started","Запущено кімнату"}.
{"Chatroom is stopped","Зупинено кімнату"}.
{"City","Місто"}.
{"Configuration","Конфігурація"}.
{"Country","Країна"}.
{"Database","База даних"}.
{"December","грудня"}.
{"Delete User","Видалити Користувача"}.
{"Dump to Text File","Копіювання в текстовий файл"}.
{"Email","Електронна пошта"}.
{"Encoding for server ~b","Кодування для сервера ~b"}.
{"End User Session","Закінчити Сеанс Користувача"}.
{"Enter the text you see","Введіть текст, що ви бачите"}.
{"Family Name","Прізвище"}.
{"February","лютого"}.
{"Friday","П'ятниця"}.
{"From ~s","Від ~s"}.
{"Full Name","Повне ім'я"}.
{"Get Number of Online Users","Отримати Кількість Підключених Користувачів"}.
{"Get Number of Registered Users","Отримати Кількість Зареєстрованих Користувачів"}.
{"Get User Last Login Time","Отримати Час Останнього Підключення Користувача"}.
{"Get User Password","Отримати Пароль Користувача"}.
{"Get User Statistics","Отримати Статистику по Користувачу"}.
{"has been banned","заборонили вхід в кімнату"}.
{"has been kicked because of an affiliation change","вигнано з кімнати внаслідок зміни рангу"}.
{"has been kicked because of a system shutdown","вигнано з кімнати внаслідок зупинки системи"}.
{"has been kicked because the room has been changed to members-only","вигнано з кімнати тому, що вона стала тільки для учасників"}.
{"has been kicked","вигнали з кімнати"}.
{" has set the subject to: "," встановив(ла) тему: "}.
{"Import Directory","Імпорт з директорії"}.
{"Import File","Імпорт з файла"}.
{"is now known as","змінив(ла) псевдонім на"}.
{"Jabber ID","Jabber ID"}.
{"January","січня"}.
{"joins the room","увійшов(ла) в кімнату"}.
{"July","липня"}.
{"June","червня"}.
{"leaves the room","вийшов(ла) з кімнати"}.
{"March","березня"}.
{"May","травня"}.
{"Middle Name","По-батькові"}.
{"Monday","Понеділок"}.
{"Name","Назва"}.
{"Nickname","Псевдонім"}.
{"November","листопада"}.
{"October","грудня"}.
{"Organization Name","Назва організації"}.
{"Organization Unit","Відділ організації"}.
{"Password ~b","Пароль ~b"}.
{"Ping","Пінг"}.
{"Port ~b","Порт ~b"}.
{"private, ","приватна, "}.
{"Restart Service","Перезапустити Сервіс"}.
{"Restore","Відновлення з резервної копії"}.
{"Room Configuration","Конфігурація кімнати"}.
{"Room Occupants","Учасники кімнати"}.
{"Saturday","Субота"}.
{"Search Results for ","Результати пошуку в "}.
{"September","вересня"}.
{"Server ~b","Сервер ~b"}.
{"Shut Down Service","Вимкнути Сервіс"}.
{"Start Modules","Запуск модулів"}.
{"Stop Modules","Зупинка модулів"}.
{"Sunday","Неділя"}.
{"The CAPTCHA is valid.","Перевірку капчею закінчено успішно"}.
{"This IP address is blacklisted in ~s","Ця IP адреса у чорному списку ~s"}.
{"Thursday","Четвер"}.
{"Too many (~p) failed authentications from this IP address (~s). The address will be unblocked at ~s UTC","Забагато  (~p) помилок авторизації з цієї IP адреси (~s). Адресу буде розблоковано о ~s UTC"}.
{"To ~s","До ~s"}.
{"Tuesday","Вівторок"}.
{"Wednesday","Середа"}.
