%% -*- coding: latin-1 -*-
{"Access Control Lists","Danh Sách Kiểm Soát Truy Cập"}.
{"Access Rules","Quy Tắc Truy Cập"}.
{"Add User","Thêm Người Sử Dụng"}.
{"April","Tháng Tư"}.
{"August","Tháng Tám"}.
{"Backup","Sao lưu dự phòng"}.
{"Birthday","Ngày sinh"}.
{"Change User Password","Thay Đổi Mật Khẩu Người Sử Dụng"}.
{"Chatroom configuration modified","Cấu hình phòng trò chuyện được chỉnh sửa"}.
{"City","Thành phố"}.
{"Configuration","Cấu hình"}.
{"Country","Quốc gia"}.
{"Database","Cơ sở dữ liệu"}.
{"December","Tháng Mười Hai"}.
{"Delete User","Xóa Người Sử Dụng"}.
{"Dump to Text File","Kết xuất ra Tập Tin Văn Bản"}.
{"Email","Email"}.
{"End User Session","Kết Thúc Phiên Giao Dịch Người Sử Dụng"}.
{"Family Name","Họ"}.
{"February","Tháng Hai"}.
{"Friday","Thứ Sáu"}.
{"From ~s","Nhận từ ~s"}.
{"Full Name","Tên Đầy Đủ"}.
{"Get Number of Online Users","Nhận Số Người Sử Dụng Trực Tuyến"}.
{"Get Number of Registered Users","Nhận Số Người Sử Dụng Đã Đăng Ký"}.
{"Get User Last Login Time","Nhận Thời Gian Đăng Nhập Cuối Cùng Của Người Sử Dụng"}.
{"Get User Password","Nhận Mật Khẩu Người Sử Dụng"}.
{"Get User Statistics","Nhận Thông Tin Thống Kê Người Sử Dụng"}.
{"has been banned","đã bị cấm"}.
{"has been kicked","đã bị đẩy ra khỏi"}.
{" has set the subject to: "," đã đặt chủ đề thành: "}.
{"Import Directory","Nhập Thư Mục"}.
{"Import File","Nhập Tập Tin"}.
{"is now known as","bây giờ được biết như"}.
{"Jabber ID","Jabber ID"}.
{"January","Tháng Một"}.
{"joins the room","tham gia phòng này"}.
{"July","Tháng Bảy"}.
{"June","Tháng Sáu"}.
{"leaves the room","rời khỏi phòng này"}.
{"March","Tháng Ba"}.
{"May","Tháng Năm"}.
{"Middle Name","Họ Đệm"}.
{"Monday","Thứ Hai"}.
{"Name","Tên"}.
{"Nickname","Bí danh"}.
{"November","Tháng Mười Một"}.
{"October","Tháng Mười"}.
{"Organization Name","Tên Tổ Chức"}.
{"Organization Unit","Bộ Phận"}.
{"Ping","Ping"}.
{"private, ","riêng,"}.
{"Restart Service","Khởi Động Lại Dịch Vụ"}.
{"Restore","Khôi phục"}.
{"Room Configuration","Cấu Hình Phòng"}.
{"Saturday","Thứ Bảy"}.
{"Search Results for ","Kết Quả Tìm Kiếm cho "}.
{"September","Tháng Chín"}.
{"Shut Down Service","Tắt Dịch Vụ"}.
{"Start Modules","Môđun Khởi Động"}.
{"Stop Modules","Môđun Dừng"}.
{"Sunday","Chủ Nhật"}.
{"Thursday","Thứ Năm"}.
{"To ~s","Gửi đến ~s"}.
{"Tuesday","Thứ Ba"}.
{"Wednesday","Thứ Tư"}.
