%% -*- coding: latin-1 -*-
{"Access Control Lists","Droets (ACL)"}.
{"Access Rules","Rîles d' accès"}.
{"Add User","Radjouter èn uzeu"}.
{"April","avri"}.
{"August","awousse"}.
{"Backup","Copeye di såvrité"}.
{"Birthday","Date d' askepiaedje"}.
{"Change User Password","Candjî l' sicret d' l' uzeu"}.
{"Chatroom configuration modified","L' apontiaedje del såle di berdelaedje a candjî"}.
{"Chatroom is created","Li såle di berdelaedje est ahivêye"}.
{"Chatroom is destroyed","Li såle di berdelaedje est distrûte"}.
{"Chatroom is started","Li såle di berdelaedje est enondêye"}.
{"Chatroom is stopped","Li såle di berdelaedje est ahotêye"}.
{"City","Veye"}.
{"Configuration","Apontiaedjes"}.
{"Country","Payis"}.
{"Database","Båze di dnêyes"}.
{"December","decimbe"}.
{"Delete User","Disfacer èn uzeu"}.
{"Dump to Text File","Schaper en on fitchî tecse"}.
{"Email","Emile"}.
{"Encoding for server ~b","Ecôdaedje pol sierveu ~b"}.
{"End User Session","Fini l' session d' l' uzeu"}.
{"Enter the text you see","Tapez l' tecse ki vos voeyoz"}.
{"Family Name","No d' famile"}.
{"February","fevrî"}.
{"Friday","vénrdi"}.
{"From ~s","Dispoy ~s"}.
{"Full Name","No etir"}.
{"Get Number of Online Users","Riçure li nombe d' uzeus raloyîs"}.
{"Get Number of Registered Users","Riçure li nombe d' uzeus edjîstrés"}.
{"Get User Last Login Time","Riçure li date/eure do dierin elodjaedje di l' uzeu"}.
{"Get User Password","Riçure sicret d' l' uzeu"}.
{"Get User Statistics","Riçure les statistikes di l' uzeu"}.
{"has been banned","a stî bani"}.
{"has been kicked","a stî pité evoye"}.
{"has been kicked because of an affiliation change","a stî pité evoye cåze d' on candjmint d' afiyaedje"}.
{"has been kicked because of a system shutdown","a stî pité evoye cåze d' èn arestaedje do sistinme"}.
{"has been kicked because the room has been changed to members-only","a stî pité evoye cåze ki l' såle a stî ristrindowe åzès mimbes seulmint"}.
{" has set the subject to: "," a candjî l' tite a: "}.
{"Import Directory","Sititchî d' on ridant"}.
{"Import File","Sititchî d' on fitchî"}.
{"is now known as","est asteure kinoxhou come"}.
{"Jabber ID","ID Jabber"}.
{"January","djanvî"}.
{"joins the room","arive sol såle"}.
{"July","djulete"}.
{"June","djun"}.
{"leaves the room","cwite li såle"}.
{"March","måss"}.
{"May","may"}.
{"Middle Name","No do mitan"}.
{"Monday","londi"}.
{"Name","No"}.
{"Nickname","Metou no"}.
{"November","nôvimbe"}.
{"October","octôbe"}.
{"Organization Name","No d' l' organizåcion"}.
{"Organization Unit","Unité d' l' organizåcion"}.
{"Password ~b","Sicret ~b"}.
{"Ping","Ping"}.
{"Port ~b","Pôrt ~b"}.
{"private, ","privé, "}.
{"Restart Service","Renonder siervice"}.
{"Restore","Rapexhî"}.
{"Room Configuration","Apontiaedje del såle"}.
{"Room Occupants","Prezints el såle"}.
{"Saturday","semdi"}.
{"Search Results for ","Rizultats do cweraedje po "}.
{"September","setimbe"}.
{"Server ~b","Sierveu ~b"}.
{"Shut Down Service","Arester siervice"}.
{"Start Modules","Enonder des modules"}.
{"Stop Modules","Arester des modules"}.
{"Sunday","dimegne"}.
{"The CAPTCHA is valid.","Li CAPTCHA est valide."}.
{"This IP address is blacklisted in ~s","Ciste adresse IP est so ene noere djivêye e ~s"}.
{"Thursday","djudi"}.
{"Too many (~p) failed authentications from this IP address (~s). The address will be unblocked at ~s UTC","I gn a-st avou pår trop (~p) d' otintifiaedjes k' ont fwait berwete vinant di ciste adresse IP la (~s). L' adresse serè disblokêye a ~s UTC"}.
{"To ~s","Viè ~s"}.
{"Tuesday","mårdi"}.
{"Wednesday","mierkidi"}.
