%% -*- coding: latin-1 -*-
{"Access Control Lists","访问控制列表(ACL)"}.
{"Access Rules","访问规则"}.
{"Add User","添加用户"}.
{"April","四月"}.
{"August","八月"}.
{"Backup","备份"}.
{"Birthday","出生日期"}.
{"Change User Password","更改用户密码"}.
{"Chatroom configuration modified","聊天室配置已修改"}.
{"Chatroom is created","聊天室已被创建"}.
{"Chatroom is destroyed","聊天室已被销毁"}.
{"Chatroom is started","聊天室已被启动"}.
{"Chatroom is stopped","聊天室已被停用"}.
{"City","城市"}.
{"Configuration","配置"}.
{"Country","国家"}.
{"Database","数据库"}.
{"December","十二月"}.
{"Delete User","删除用户"}.
{"Dump to Text File","转储到文本文件"}.
{"Email","电子邮件"}.
{"Encoding for server ~b","服务器~b的编码"}.
{"End User Session","结束用户会话"}.
{"Enter the text you see","请输入您所看到的文本"}.
{"Family Name","姓氏"}.
{"February","二月"}.
{"Friday","星期五"}.
{"From ~s","来自~s"}.
{"Full Name","全名"}.
{"Get Number of Online Users","获取在线用户数"}.
{"Get Number of Registered Users","获取注册用户数"}.
{"Get User Last Login Time","获取用户上次登陆时间"}.
{"Get User Password","获取用户密码"}.
{"Get User Statistics","获取用户统计"}.
{"has been banned","已被禁止"}.
{"has been kicked because of an affiliation change","因联属关系改变而被踢出"}.
{"has been kicked because of a system shutdown","因系统关机而被踢出"}.
{"has been kicked because the room has been changed to members-only","因该房间改为只对会员开放而被踢出"}.
{"has been kicked","已被踢出"}.
{" has set the subject to: ","已将标题设置为: "}.
{"Import Directory","导入目录"}.
{"Import File","导入文件"}.
{"is now known as","现在称呼为"}.
{"Jabber ID","Jabber ID"}.
{"January","一月"}.
{"joins the room","加入房间"}.
{"July","七月"}.
{"June","六月"}.
{"leaves the room","离开房间"}.
{"March","三月"}.
{"May","五月"}.
{"Middle Name","中间名"}.
{"Monday","星期一"}.
{"Name","姓名"}.
{"Nickname","昵称"}.
{"November","十一月"}.
{"October","十月"}.
{"Organization Name","组织名称"}.
{"Organization Unit","组织单位"}.
{"Password ~b","~b的密码"}.
{"Ping","Ping"}.
{"Port ~b","~b的端口"}.
{"private, ","保密, "}.
{"Restart Service","重启服务"}.
{"Restore","恢复"}.
{"Room Configuration","房间配置"}.
{"Room Occupants","房间人数"}.
{"Saturday","星期六"}.
{"Search Results for ","搜索结果属于关键词 "}.
{"September","九月"}.
{"Server ~b","服务器~b"}.
{"Shut Down Service","关闭服务"}.
{"Start Modules","启动模块"}.
{"Stop Modules","停止模块"}.
{"Sunday","星期天"}.
{"The CAPTCHA is valid.","验证码有效."}.
{"This IP address is blacklisted in ~s","此IP地址在~s中已被列入黑名单"}.
{"Thursday","星期四"}.
{"Too many (~p) failed authentications from this IP address (~s). The address will be unblocked at ~s UTC","来自IP地址(~p)的(~s)失败认证太多. 该地址将在UTC时间~s被禁用."}.
{"To ~s","发送给~s"}.
{"Tuesday","星期二"}.
{"Wednesday","星期三"}.
