{spec, last,
 #spec{name = <<"query">>,
       min = 0, max = 1,
       xmlns = <<"jabber:iq:last">>,
       result = {last, '$seconds', '$text'},
       attrs = [#attr{name = <<"seconds">>,
                      default = undefined,
                      enc = {enc_int, []},
                      dec = {dec_int, [0, infinity]}}],
       cdata = #cdata{label = '$text'}}}.

{spec, version,
 #spec{name = <<"query">>,
       xmlns = <<"jabber:iq:version">>,
       min = 0, max = 1,
       result = {version, '$name', '$version', '$os'},
       els = [#spec{name = <<"name">>,
                    min = 1,
                    max = 1,
                    result = '$cdata',
                    cdata = #cdata{label = '$cdata', required = true}},
              #spec{name = <<"version">>,
                    min = 1,
                    max = 1,
                    result = '$cdata',
                    cdata = #cdata{label = '$cdata', required = true}},
              #spec{name = <<"os">>,
                    max = 1,
                    result = '$cdata',
                    cdata = #cdata{label = '$cdata', required = true}}]}}.

{spec, roster,
 #spec{name = <<"query">>,
       xmlns = <<"jabber:iq:roster">>,
       result = {roster, '$item', '$ver'},
       min = 0, max = 1,
       attrs = [#attr{name = <<"ver">>}],
       els = [#spec{name = <<"item">>,
                    result = {item, '$jid', '$name',
                              '$groups', '$subscription', '$ask'},
                    attrs = [#attr{name = <<"jid">>,
                                   required = true},
                             #attr{name = <<"name">>},
                             #attr{name = <<"subscription">>,
                                   default = none,
                                   enc = {enc_enum, []},
                                   dec = {dec_enum, [[none,to,from,both,remove]]}},
                             #attr{name = <<"ask">>,
                                   default = undefined,
                                   enc = {enc_enum, []},
                                   dec = {dec_enum, [[subscribe]]}}],
                    els = [#spec{name = <<"group">>,
                                 label = '$groups',
                                 result = '$cdata',
                                 cdata = #cdata{required = true,
                                                label = '$cdata'}}]}]}}.

{spec, disco_info,
 #spec{name = <<"query">>,
       min = 0, max = 1,
       xmlns = <<"http://jabber.org/protocol/disco#info">>,
       result = {disco_info, '$identity', '$feature'},
       els = [#spec{name = <<"identity">>,
                    result = {'$category', '$type', '$name'},
                    attrs = [#attr{name = <<"category">>,
                                   required = true},
                             #attr{name = <<"type">>,
                                   required = true},
                             #attr{name = <<"name">>}]},
              #spec{name = <<"feature">>,
                    result = '$var',
                    attrs = [#attr{name = <<"var">>,
                                   required = true}]}]}}.

{spec, disco_items,
 #spec{name = <<"query">>,
       min = 0, max = 1,
       xmlns = <<"http://jabber.org/protocol/disco#items">>,
       result = {disco_items, '$node', '$item'},
       attrs = [#attr{name = <<"node">>}],
       els = [#spec{name = <<"item">>,
                    result = {'$jid', '$name', '$node'},
                    cdata = #cdata{label = '$cdata'},
                    attrs = [#attr{name = <<"jid">>,
                                   dec = {dec_jid, []},
                                   enc = {enc_jid, []},
                                   required = true},
                             #attr{name = <<"name">>},
                             #attr{name = <<"node">>}]}]}}.

{spec, stats,
 #spec{name = <<"query">>,
       min = 0, max = 1,
       xmlns = <<"http://jabber.org/protocol/stats">>,
       result = {stats, '$stat'},
       els = [#spec{name = <<"stat">>,
                    result = {stat, '$name', '$units', '$value', '$error'},
                    attrs = [#attr{name = <<"name">>,
                                   required = true},
                             #attr{name = <<"units">>},
                             #attr{name = <<"value">>}],
                    els = [#spec{name = <<"error">>,
                                 result = {'$code', '$cdata'},
                                 attrs = [#attr{name = <<"code">>,
                                                required = true,
                                                enc = {enc_int, []},
                                                dec = {dec_int, []}}]}]}]}}.

{spec, iq,
 #spec{name = <<"iq">>,
       min = 0, max = 1,
       result = {'Iq', '$id', '$type', '$lang', '$from', '$to',
                 '$error', '$_els'},
       attrs = [#attr{name = <<"id">>,
                      required = true},
                #attr{name = <<"type">>,
                      required = true,
                      enc = {enc_enum, []},
                      dec = {dec_enum, [[get, set, result, error]]}},
                #attr{name = <<"from">>,
                      dec = {dec_jid, []},
                      enc = {enc_jid, []}},
                #attr{name = <<"to">>,
                      dec = {dec_jid, []},
                      enc = {enc_jid, []}},
                #attr{name = <<"xml:lang">>,
                      label = '$lang'}],
       els = [error]}}.

{spec, message,
 #spec{name = <<"message">>,
       min = 0, max = 1,
       result = {'Message', '$id', '$type', '$lang', '$from', '$to',
                 '$subject', '$body', '$thread', '$error', '$_els'},
       attrs = [#attr{name = <<"id">>},
                #attr{name = <<"type">>,
                      default = normal,
                      enc = {enc_enum, []},
                      dec = {dec_enum, [[chat, normal, groupchat,
                                         headline, error]]}},
                #attr{name = <<"from">>,
                      dec = {dec_jid, []},
                      enc = {enc_jid, []}},
                #attr{name = <<"to">>,
                      dec = {dec_jid, []},
                      enc = {enc_jid, []}},
                #attr{name = <<"xml:lang">>,
                      label = '$lang'}],
       els = [error,
              #spec{name = <<"subject">>,
                    result = {'$subject_lang', '$cdata'},
                    attrs = [#attr{name = <<"xml:lang">>,
                                   label = '$subject_lang'}]},
              #spec{name = <<"body">>,
                    result = {'$body_lang', '$cdata'},
                    attrs = [#attr{name = <<"xml:lang">>,
                                   label = '$body_lang'}]},
              #spec{name = <<"thread">>,
                    min = 0, max = 1,
                    result = '$cdata'}]}}.

{spec, presence,
 #spec{name = <<"presence">>,
       min = 0, max = 1,
       result = {'Presence', '$id', '$type', '$lang', '$from', '$to',
                 '$show', '$status', '$priority', '$error', '$_els'},
       attrs = [#attr{name = <<"id">>},
                #attr{name = <<"type">>,
                      enc = {enc_enum, []},
                      dec = {dec_enum, [[unavailable, subscribe, subscribed,
                                         unsubscribe, unsubscribed,
                                         probe, error]]}},
                #attr{name = <<"from">>,
                      dec = {dec_jid, []},
                      enc = {enc_jid, []}},
                #attr{name = <<"to">>,
                      dec = {dec_jid, []},
                      enc = {enc_jid, []}},
                #attr{name = <<"xml:lang">>,
                      label = '$lang'}],
       els = [error,
              #spec{name = <<"show">>,
                    min = 0, max = 1,
                    result = '$cdata',
                    cdata = #cdata{enc = {enc_enum, []},
                                   dec = {dec_enum, [[away, chat, dnd, xa]]}}},
              #spec{name = <<"status">>,
                    result = {'$status_lang', '$cdata'},
                    attrs = [#attr{name = <<"xml:lang">>,
                                   label = '$status_lang'}]},
              #spec{name = <<"priority">>,
                    min = 0, max = 1,
                    result = '$cdata',
                    cdata = #cdata{enc = {enc_int, []},
                                   dec = {dec_int, [-128, 127]}}}]}}.

{spec, error,
 #spec{name = <<"error">>,
       min = 0, max = 1,
       result = {error, '$error_type', '$by', '$reason', '$text'},
       attrs = [#attr{name = <<"type">>,
                      label = '$error_type',
                      required = true,
                      dec = {dec_enum, [[auth, cancel, continue,
                                         modify, wait]]},
                      enc = {enc_enum, []}},
                #attr{name = <<"by">>}],
       els = [#spec{name = <<"text">>,
                    min = 0, max = 1,
                    result = {'$text_lang', '$cdata'},
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-stanzas">>,
                    attrs = [#attr{name = <<"xml:lang">>,
                                   label = '$text_lang'}]},
              #spec{name = <<"bad-request">>, 
                    result = 'bad-request',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-stanzas">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"conflict">>, 
                    result = 'conflict',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-stanzas">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"feature-not-implemented">>, 
                    result = 'feature-not-implemented',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-stanzas">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"forbidden">>, 
                    result = 'forbidden',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-stanzas">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"gone">>, 
                    result = {'gone', '$cdata'},
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-stanzas">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"internal-server-error">>, 
                    result = 'internal-server-error',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-stanzas">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"item-not-found">>, 
                    result = 'item-not-found',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-stanzas">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"jid-malformed">>, 
                    result = 'jid-malformed',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-stanzas">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"not-acceptable">>, 
                    result = 'not-acceptable',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-stanzas">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"not-allowed">>, 
                    result = 'not-allowed',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-stanzas">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"not-authorized">>, 
                    result = 'not-authorized',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-stanzas">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"policy-violation">>, 
                    result = 'policy-violation',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-stanzas">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"recipient-unavailable">>, 
                    result = 'recipient-unavailable',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-stanzas">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"redirect">>, 
                    result = {'redirect', '$cdata'},
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-stanzas">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"registration-required">>, 
                    result = 'registration-required',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-stanzas">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"remote-server-not-found">>, 
                    result = 'remote-server-not-found',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-stanzas">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"remote-server-timeout">>, 
                    result = 'remote-server-timeout',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-stanzas">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"resource-constraint">>, 
                    result = 'resource-constraint',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-stanzas">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"service-unavailable">>, 
                    result = 'service-unavailable',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-stanzas">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"subscription-required">>, 
                    result = 'subscription-required',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-stanzas">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"undefined-condition">>, 
                    result = 'undefined-condition',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-stanzas">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"unexpected-request">>, 
                    result = 'unexpected-request',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-stanzas">>,
                    min = 0, max = 1, label = '$reason'}]}}.
                     
{spec, bind,
 #spec{name = <<"bind">>,
       xmlns = <<"urn:ietf:params:xml:ns:xmpp-bind">>,
       min = 0, max = 1,
       result = {bind, '$jid', '$resource'},
       els = [#spec{name = <<"jid">>,
                    min = 0, max = 1,
                    result = '$cdata',
                    cdata = #cdata{dec = {dec_jid, []},
                                   enc = {enc_jid, []}}},
              #spec{name = <<"resource">>,
                    min = 0, max = 1,
                    result = '$cdata',
                    cdata = #cdata{dec = {resourceprep, []},
                                   enc = {resourceprep, []}}}]}}.

{spec, sasl_auth,
 #spec{name = <<"auth">>,
       xmlns = <<"urn:ietf:params:xml:ns:xmpp-sasl">>,
       min = 0, max = 1,
       cdata = #cdata{dec = {base64, decode, []},
                      enc = {base64, encode, []}},
       result = {sasl_auth, '$mechanism', '$cdata'},
       attrs = [#attr{name = <<"mechanism">>,
                      required = true}]}}.

{spec, sasl_abort,
 #spec{name = <<"abort">>,
       xmlns = <<"urn:ietf:params:xml:ns:xmpp-sasl">>,
       min = 0, max = 1,
       result = {sasl_abort}}}.

{spec, sasl_challenge,
 #spec{name = <<"challenge">>,
       xmlns = <<"urn:ietf:params:xml:ns:xmpp-sasl">>,
       min = 0, max = 1,
       cdata = #cdata{dec = {base64, decode, []},
                      enc = {base64, encode, []}},
       result = {sasl_challenge, '$cdata'}}}.

{spec, sasl_response,
 #spec{name = <<"response">>,
       xmlns = <<"urn:ietf:params:xml:ns:xmpp-sasl">>,
       min = 0, max = 1,
       cdata = #cdata{dec = {base64, decode, []},
                      enc = {base64, encode, []}},
       result = {sasl_response, '$cdata'}}}.

{spec, sasl_success,
 #spec{name = <<"success">>,
       xmlns = <<"urn:ietf:params:xml:ns:xmpp-sasl">>,
       min = 0, max = 1,
       cdata = #cdata{dec = {base64, decode, []},
                      enc = {base64, encode, []}},
       result = {sasl_success, '$cdata'}}}.

{spec, sasl_failure,
 #spec{name = <<"failure">>,
       xmlns = <<"urn:ietf:params:xml:ns:xmpp-sasl">>,
       min = 0, max = 1,
       result = {sasl_failure, '$reason', '$text'},
       els = [#spec{name = <<"text">>,
                    min = 0, max = 1,
                    result = {'$text_lang', '$cdata'},
                    attrs = [#attr{name = <<"xml:lang">>,
                                   label = '$text_lang'}]},
              #spec{name = <<"aborted">>,
                    result = 'aborted',
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"account-disabled">>,
                    result = 'account-disabled',
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"credentials-expired">>,
                    result = 'credentials-expired',
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"encryption-required">>,
                    result = 'encryption-required',
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"incorrect-encoding">>,
                    result = 'incorrect-encoding',
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"invalid-authzid">>,
                    result = 'invalid-authzid',
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"invalid-mechanism">>,
                    result = 'invalid-mechanism',
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"malformed-request">>,
                    result = 'malformed-request',
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"mechanism-too-weak">>,
                    result = 'mechanism-too-weak',
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"not-authorized">>,
                    result = 'not-authorized',
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"temporary-auth-failure">>,
                    result = 'temporary-auth-failure',
                    min = 0, max = 1, label = '$reason'}]}}.

{spec, sasl_mechanism,
 #spec{name = <<"mechanism">>,
       result = '$cdata',
       min = 1,
       cdata = #cdata{}}}.

{spec, sasl_mechanisms,
 #spec{name = <<"mechanisms">>,
       xmlns = <<"urn:ietf:params:xml:ns:xmpp-sasl">>,
       result = {sasl_mechanisms, '$mechanism'},
       min = 0, max = 1,
       els = [sasl_mechanism]}}.

{spec, starttls,
 #spec{name = <<"starttls">>,
       xmlns = <<"urn:ietf:params:xml:ns:xmpp-tls">>,
       min = 0, max = 1,
       result = {starttls, '$required'},
       els = [#spec{name = <<"required">>,
                    min = 0, max = 1,
                    default = false,
                    result = true}]}}.

{spec, starttls_proceed,
 #spec{name = <<"proceed">>,
       xmlns = <<"urn:ietf:params:xml:ns:xmpp-tls">>,
       min = 0, max = 1,
       result = {starttls_proceed}}}.

{spec, starttls_failure,
 #spec{name = <<"failure">>,
       xmlns = <<"urn:ietf:params:xml:ns:xmpp-tls">>,
       min = 0, max = 1,
       result = {starttls_failure}}}.

{spec, stream_features,
 #spec{name = <<"stream:features">>,
       min = 0, max = 1,
       result = {stream_features, '$_els'}}}.

{spec, p1_push,
 #spec{name = <<"push">>,
       min = 0, max = 1,
       result = {p1_push},
       xmlns = <<"p1:push">>}}.

{spec, p1_rebind,
 #spec{name = <<"rebind">>,
       min = 0, max = 1,
       result = {p1_rebind},
       xmlns = <<"p1:rebind">>}}.

{spec, p1_ack,
 #spec{name = <<"ack">>,
       min = 0, max = 1,
       result = {p1_ack},
       xmlns = <<"p1:ack">>}}.

{spec, caps,
 #spec{name = <<"c">>,
       min = 0, max = 1,
       xmlns = <<"http://jabber.org/protocol/caps">>,
       result = {caps, '$hash', '$node', '$ver'},
       attrs = [#attr{name = <<"hash">>},
                #attr{name = <<"node">>},
                #attr{name = <<"ver">>,
                      enc = {base64, encode, []},
                      dec = {base64, decode, []}}]}}.

{spec, register,
 #spec{name = <<"register">>,
       min = 0, max = 1,
       xmlns = <<"http://jabber.org/features/iq-register">>,
       result = {register}}}.

{spec, session,
 #spec{name = <<"session">>,
       min = 0, max = 1,
       xmlns = <<"urn:ietf:params:xml:ns:xmpp-session">>,
       result = {session}}}.

{spec, ping,
 #spec{name = <<"ping">>,
       min = 0, max = 1,
       xmlns = <<"urn:xmpp:ping">>,
       result = {ping}}}.

{spec, time,
 #spec{name = <<"time">>,
       min = 0, max = 1,
       xmlns = <<"urn:xmpp:time">>,
       result = {time, '$tzo', '$utc'},
       els = [#spec{name = <<"tzo">>,
                    min = 1, max = 1,
                    result = '$cdata',
                    cdata = #cdata{dec = {dec_tzo, []},
                                   enc = {enc_tzo, []}}},
              #spec{name = <<"utc">>,
                    min = 1, max = 1,
                    result = '$cdata',
                    cdata = #cdata{dec = {dec_utc, []},
                                   enc = {enc_utc, []}}}]}}.

{spec, stream_error,
 #spec{name = <<"stream:error">>,
       min = 0, max = 1,
       result = {stream_error, '$reason', '$text'},
       els = [#spec{name = <<"text">>,
                    min = 0, max = 1,
                    result = {'$text_lang', '$cdata'},
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-streams">>,
                    attrs = [#attr{name = <<"xml:lang">>,
                                   label = '$text_lang'}]},
              #spec{name = <<"bad-format">>,
                    result = 'bad-format',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-streams">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"bad-namespace-prefix">>,
                    result = 'bad-namespace-prefix',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-streams">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"conflict">>,
                    result = 'conflict',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-streams">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"connection-timeout">>,
                    result = 'connection-timeout',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-streams">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"host-gone">>,
                    result = 'host-gone',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-streams">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"host-unknown">>,
                    result = 'host-unknown',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-streams">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"improper-addressing">>,
                    result = 'improper-addressing',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-streams">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"internal-server-error">>,
                    result = 'internal-server-error',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-streams">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"invalid-from">>,
                    result = 'invalid-from',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-streams">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"invalid-id">>,
                    result = 'invalid-id',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-streams">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"invalid-namespace">>,
                    result = 'invalid-namespace',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-streams">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"invalid-xml">>,
                    result = 'invalid-xml',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-streams">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"not-authorized">>,
                    result = 'not-authorized',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-streams">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"not-well-formed">>,
                    result = 'not-well-formed',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-streams">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"policy-violation">>,
                    result = 'policy-violation',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-streams">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"remote-connection-failed">>,
                    result = 'remote-connection-failed',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-streams">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"reset">>,
                    result = 'reset',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-streams">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"resource-constraint">>,
                    result = 'resource-constraint',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-streams">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"restricted-xml">>,
                    result = 'restricted-xml',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-streams">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"see-other-host">>,
                    result = 'see-other-host',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-streams">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"system-shutdown">>,
                    result = 'system-shutdown',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-streams">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"undefined-condition">>,
                    result = 'undefined-condition',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-streams">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"unsupported-encoding">>,
                    result = 'unsupported-encoding',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-streams">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"unsupported-stanza-type">>,
                    result = 'unsupported-stanza-type',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-streams">>,
                    min = 0, max = 1, label = '$reason'},
              #spec{name = <<"unsupported-version">>,
                    result = 'unsupported-version',
                    xmlns = <<"urn:ietf:params:xml:ns:xmpp-streams">>,
                    min = 0, max = 1, label = '$reason'}
             ]}}.

dec_tzo(Val) ->
    [H1, M1] = str:tokens(Val, <<":">>),
    H = erlang:binary_to_integer(H1),
    M = erlang:binary_to_integer(M1),
    if H >= -12, H =< 12, M >= 0, M < 60  ->
            {H, M}
    end.

enc_tzo({Sign, {H, M}}) ->
    Sign = if H >= 0 ->
                   <<>>;
              true ->
                   <<"-">>
           end,
    list_to_binary([Sign, io_lib:format("~2..0w:~2..0w", [H, M])]).

dec_utc(Val) ->
    {_, _, _} = jlib:datetime_string_to_timestamp(Val).

enc_utc(Val) ->
    jlib:now_to_utc_string(Val).

dec_jid(Val) ->
    case jlib:string_to_jid(Val) of
        error ->
            erlang:error(badarg);
        J ->
            J
    end.

enc_jid(J) ->            
    jlib:jid_to_string(J).

resourceprep(R) ->
    case jlib:resourceprep(R) of
        error ->
            erlang:error(badarg);
        R1 ->
            R1
    end.

sign(N) when N < 0 -> <<"-">>;
sign(_) -> <<"+">>.

%% Local Variables:
%% mode: erlang
%% End:
%% vim: set filetype=erlang tabstop=8:
